---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgAmF2/nR3Q7grxmKWTImLZY75ptF0kQaJgILyxrM9bXL918Jx9o/Z/SV+LslkIkrCXXiFFEouemkc2rKM5q8FUcCSGrWCXzKQXaRsVtqbAeI5Z/yO5ViivkZeKLaB0Gpu/4uFDnSiLVLEnmzYXpZIq50OuhaZq6BFXhP5dqbZAzGLA47E4VKlFGQ49lnz5Ojlbe0TpU2u2yR7VTghk8Iy3wNtkbf43vsr32aUY8TOItGs/3V7NRofyMDldw2ojd3XNmNgGQp5o71kFBHcumjB+/Cw9RsJzk4LhnWjw7iktTwJKUg7XtezmCucYwO5ZnNOeaBzw6c0AhTkUssXB0o3FIcr1wrz43SZA775svgvO8uf8Q+3vFOzFl6lGcCR+yH3qz4UShFSrm76QwQ/wGFzExoop6EXX2dEgMvD8dXFn/mRDaYnEbI13+8JsNw5BFTpE7qFPvwoU6Jpkxda4wLY1tuui9atsaqorlA60YAuETRt+6AlUbBCIUmq9HE8hKVAQklozZB+CYR6An0nzT8LcTCrjPI8imFWNEzeAaOlnB2YFnf7gyAtOAwpWu8QjpzIlHw1TSkyicQTt9Ez2nV2OFzw0XW0Y9ZYfcn/jc27B5tEUp/3h76thZfY5UrfETS6IS68qJI8ktERrPMHiXx53wMCQ3BWMc44oyJdrlw1+ZLsiLNHZ40GpwXKfyu/wj5+OZ57GrbveYFDBFVJQZrK747h8T
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
