---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgCqMjtYVBAhfg5wFgzUtlVycDvD9keqzKdPbzylmubqC4qWU2YCZR2aZmLiX3c3F/zcqxVBI4N+ClRuMmUVi05gRi9fsnFSJZBboq7FeODsLoZV5TKVplzes5RlJkVWqdhC586mHU5wbwfCAez38xooel/aEns9W9PYihPhewk50w+3+hS5cfLhBRLJkzlJ1vXWxeggT8EhLU9fJlM7CLJtdbz8DjQ36cwylBijc7TL35SFvGjV5eYC/xPKZxiOsRrXlFOiTYF+UDCozn+EUQ3Wdv3JZTihm9S93dH9RL7wl3qWmYEHodnRwQBxY04KBQt0yRGCdv9i+ZnXpKDWVf4gLKuOloKSek6gL3UKMMLEdLO26+rqVi8TwdJ4xSqNC1gXdEDUXI+suLG/PJELOQWKdBzJUS0EYEFGiJxAmvy8vzCBvYbyUGxFuZKNHYIDeJ/gMgX4S9hgvgqaH835aAAqO8ScOSp4WiGphzzTYoItLlf+xS3iw25jlnkueWV1ReRzOIOIJs18LKU2TC+PhCqSQ/KiJp285PV5SoTeLBE2B5bZTVAsFCTxqXWxN+asO+otmeBWCLLR5GB66QUqwCLHYTJb6NOLr3khM05XRiDXgPcqbHT0uMOMZUUOu1W6/6jg37hjicV9uv0hKjvhT53ArpQrEcG/SpmC4/gOzxFdEbz4T3B0ksge7fDkxYI8j7F3MjxZFSIwxDgpHMYzTu7ddJV5
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
