---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgBkUvRxC+2CNsbOZrFyMtlJGRAXmPiEv96pJr8HjtwBXKMJRi4yWg3FPZe4rSthVU69lfG/FmC4GYl6ZhS+CA2yIHUB7Mz7OFL8QfWFjOWeNMbnD/sQRI3MZY3HOqowKzjEMhx83g/sFrjVYEu2pLCHfNhOlEQTELGbsGTOoYS5v4c7IJgVOUX+eHybNivA6zJApTUAJpm9Ja/Yq4rKaQZgaYzRlk7ANQ64bxkqvOSy+BE0jeTKOGWNlPng6oMX6sYQwEBr3I7dfNOWt4NLa1Bt0ls+PlNw+n/Nzr+cZeU9+Qru+NWjClXSp2vfNbQH69HYB64bqbGIC+CPJJqLT/y4abOQNOAWok/ZgfR47wqGI5wt5rBsdCe9HVQcWX0HQirO5CP+O5Q44udIEtRZC4MIzWwQ0iP7So89+/bQDYKEUHMqtZf8FHLNTxGEK01MnHXSeVTipDOeBjLtdMvyTtDWAFZ6OoSw3p5xIwiL3xJhFB5tpBM5xMHQRH2byw/t/r6fkEs8CYYh0J+cItADsmWpE+S0eFfsIM0Yl04butvLAHdCafJjOJxDnibQl50jC7BlWUwrkThSL760ByLg7MHSSVxEOhTqam/i/3AXhx9M4gEcYv/h51nrnnuY+UIwPSnih935WNH6pSPZC3a6vnBp/xPoAMD1ZgcoGrSxf0zT58ycSb7vxZPZMKDZN2f1AzHH86oziFaRlXsK0ZE+QR7EjR3s
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
