---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-storefront
spec:
  encryptedData:
    .dockerconfigjson: AgDNe28LdBDMDRV8SNoA95LPBzK56ENCBo+Djmtcp3yAgBLKmcMxanLS5Lh8gE0nY6RlcQ4DeF/mktfbhE3SWSwqiTuGpZnl/eqmpMxTxfPBdPYHA5rGjFZUXR6OMcom2925N7q5Oz2k6LoaXkpo2jh0zJrhxg6prhso5liaAVV+EVkwWUeJn5Uc8zSx1GbS8tl2FZk9fNNHml8LmcyotLtK3E68cEcp7fvfhhkyS8OZaH/pE2Z4fjzX++rnTgkQw6pjO9Ak295NOM1wEk3jUO828AmnozK6Q4059BjFXqZZRddLxK+6lS6Igb4Z4ifswa2l12p+r+RnelhxSNubUQqEEDes4l9OU0vtzmROMEnG9YnQelODenoVcK5fvCjR8ABGdnD23YO1/DhSAINWKRAuPIAkmjrROsSFnOIrDbITuLfAEmCliPffMNc79xEwD+Jjp1M6o/t7A5JMNo6weyGORJgO5d1RbKdfM/74X0J4WQ3WdFGgxP5gGxL12Vz7Ll10/EzcwpCB9hW/9hkgJr9Ey+OnqqFaBGriYYOeyh7dAevAeHGaWSU0+xlMeMA3Sl/eYJVWF2Sk0e4OYZe65sOJpV7vsFUMYjfkJVYfr1pJWKH61xAONFWycsvzglWaPfKEsHzaCMwm3fSM5znSIHDCkWE4MnhidefRZMxOu63Dx0TC6KgeXW6YDiuKuRbS/QT5dXQt6Z97jF7Iv8G2j382umHhvluOEKSqX/m7mSPUmctshEVBHxjBC6h6yVp/ngJHFjIZrJqQMj18Y5yvZbft238JdKh8PFbKoEiK4BPgcLhk3jM+Fui38qtPYEDFly83WLjad6EGhQXdP0a6MOzt+MXZg7gKl0QZrV0ICDxFEm8=
  template:
    metadata:
      name: katech-registry
      namespace: katech-storefront
    type: kubernetes.io/dockerconfigjson
