---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluent-bit-secrets
  namespace: logging
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgA8JgyaSu7mW3KcRPaIuaizv21OI/cOM+rMNDMb5PG0ck59QE5jNMxNR//06ml4BFtnEoSHRjQrgvwPSK8dv154LHcHDVC/99RlM9REw8tFXew6s8rWysi17jPuW8/2/yex5QMEnCpRc+EoW0hxDMWG+2Q2VAMY7/DIjkB6J1PnhP7kO6kPgv1NgFJaguinpy0TBjIgZuahFlGaUWnY6xkLmJzkumm73kDkvJ7dwoVulrwE3yhh3N5sjx7cS+dnJuxjozowomctXz4K3PHQdGeO/dbzoK7g+hY8pcqEb6Y6HDeJucmRLbgFsI85+C2b3+mLyg02XnDGIh6Hpgd1IXQuQRym8RvJMuV0azocNvEfqca4j3hyd1tE81T66M9rGMYZlSfPLL/ezfBf+DPo6RaGFbEQeGnTQs0vO2ySeVWtiYTfcgt406k0mwE/zd4rBKkz3+hEGqZdX3wx7aidaKrFi4NnX7BMHnZ9MmPyj1z8VADkuiicr9RVqHuO5gGJH1zP+6DQGPGJBvEnyewXigUuXaTJHnr0y7d806x2hCLgjQVd0cnAvGN8MRJagKeE3VTjr9U6e8rGWX77twMCAzsVRPb2BD1pddDTiENuGHp2fU2tDvSKSOTr/J+3KtqCf7ejDoS9XCpqUGqn3K7/GuZHiQrU9c8TS8AFQN1wHGK4TfyWYik04f+bbLr2q8qyY1XB0NRwHOvSdDN4mgI=
    ELASTIC_USERNAME: AgBu4Iby6czrRpqz5egK0UvRYEufheHm9xKG+qIbNNchve2E4kbs0blVZT6T8UCXyaB+LLfXmfNJevUx91LaiC+DWE5f7evv7Pc+7bTZtGbxcpxeFpVXOHrwP9hcR/qYxzgEhXi/0lGam89vCLCWC+nQQJ9IAk4CWztJy99AOdCBlETEs84mHuGh+gbtGVypyK2aS6QtGAogNcKNFWg4q6L1txaPZbPjZMDyVVdwznpD5ukJnYq7c5Rf0R9Hf4ID78q79H6hHUkFkwz/VCT+DZUxq8Sr/JOq1H+xXrxAtuV6nUWebc4Huvnp6lxlOWBn9GKIyQJ8niLRA5dWjXyQalZ0Xmnpj6DsGIKPCjAWitxvTR7tq41HoaPVuOCUPyciGoJTxCzHLUAvQGYBTmOvBSBwV9dmA0ItUiSDAJpsuXA+LQh5tquERiSnRE4EvcUa5XvMfQXXk+ePTzPx5wAzGco+eOjg2pjkQnjwL8z7/2KG3buWyp5CVttZUC3WlhuMLJBC9D/lxAj9Rd3ijQ0eVPYgj+9zOx5rBLPPZKrT6RR8ILq+H/S2/sTNdF+ZIePTbj19zi7pqvOMhPXWFxtkfIr8taHnEGHyy8OX/5MOh7c7EYuhxjxFRyj+4u9eaClSwdHikWwhZNVFelqoYc1y40hJsixoaaVuNcfgSFqldl6GeCsSBGnalmJP18iceVdx+GwY2Va8fW10IR8=
  template:
    metadata:
      name: fluent-bit-secrets
      namespace: logging
    type: Opaque
