---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluent-bit-secrets
  namespace: logging
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgB37WpJLSctYaO80Y/6IikUHr3sXb9Dumr+fBsduO7kGY/btFQW5+Dy0FY4mBJKJpKi8RHQwB/LFl4XKOJHuEgkKA6ZYFcyNYWeSAeY/kAkRv+0iELUPW609YQQV2fm6e6oN/VxezxkSJ8pJ7WZuRxNMbTjSKZJOE0ZDV0RrXXAV6XMjVZPF+6cK81NveJj5CPJOaJhFIJbTYipweXCF61kMfXSMq7blX9AgRj+WRxAttIA1sAwacg+lXkSgPYWYKMQmPoKLmOxmR16tuV8Q6DMn0kop2K6EtNE1PizReeIuEdWKr7VMsWwCIWfVMhXKqYhDxM54eSTLCKOC3EDBKTFa86C02rlJXgvNp2I8F9CM3m3xCXFFPK1RToXjK0QFdFXmixHCBrVZBITEcdc9/VhDMRwbuSTkm5S9/91j4gVHG9c4+CtQGjtPj1vJCHwUZKTJVVj3QHbC0TEzsH4xszuSqfZ1Y6Q/S57qj+w131jDTIZJBYPnm8+tBs4G6YhBv+J1n6HHdYA1pyK2IFXGdzdDFu1/F0GjTRqauoHZ2laqiuwxw3vXZUvqiGvJTVOh52InfxL1n08yo9ojGxEXhUNpAGVhkph0SFGV7lvaWwO084CJMqQbMVJgCY0PzeiZo/AMSPg0Gor0MxALUNGDu67x139uKg0oCVJo2Eftkw0CG2+nX945qlmDEMWOqSISikQBXnmCVReYsAN45Q=
    ELASTIC_USERNAME: AgC/nagCVXqgYBynMliNfqrF11e7qlr68r0Q1HCEMqYUu6wNYJUNiSYtut3RM7YYv11fUHYiy9bn8CCTFzE/xrCVMoLgwxW5TQzTsSpRuYRdzikzQRszpkZwJKxZOJ9V+4hnJs4v5QnGoaxUKs05ZjP7ANiD3Z89dMWj3e2mA2EBJ/3HiHgi2YVA0KTFewBXwpWtN63FKfSqKXBkJzJLnkNPGBh1GNDfhu1QB+eKEpoUuxZYJusgd5MzoI017/3mwDCnOTb4W7s0FY+Ygu0SeYI4CfpZwNCNjAL+Jl92lyXATC5ta+5H60tZPTZ1t1bAkhBJkJDHBIbIu+QmZT/6N4jietkIyqRLU0XtVEdDcV0B7Zosh9iaSRPEDv19yBhqBPSmOtVXSNFZEApoLtzRpTku5pWjp3P4CEaFKIOGPagov1lH+IJMuDKPU8Y+GJWWwlDsvLRckDcpnvXReDkvOoN8nMJkdp4kbPlTPp+Hax+CQRXn/292HXhO3WWn9dhZaX+ol8Qec9HAqC76TCDAxarQBQHiEbNp3Jc0A76gmQdAxET0r8Fsr3okXVp4VePRWJdqNswDIkxEVuujnFHZy7U+zLvQ7v8UpOX2pl3n3aNz8YcSiihC4hF5ZtmL/liTp2bmXZtljN0nhTRy2MF43KmmYllMjgfO6IZMPah+8b0Da55idemozwuiWnDIJ1CsaQX8m+79O1ee+00=
  template:
    metadata:
      name: fluent-bit-secrets
      namespace: eck-system
    type: Opaque
