kind: DaemonSet

serviceAccount:
  create: true

rbac:
  create: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/custom_parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        storage.path /var/log/flb-storage
        storage.sync normal
        storage.checksum off
        storage.backlog.mem_limit 50M

  parsers: |
    [PARSER]
        Name        app_json
        Format      json
        Time_Key    @timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On

    [MULTILINE_PARSER]
        Name          spring_java_multiline
        Type          regex
        Flush_Timeout 2000

        Rule      "start_state"  "/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}([.,]\d{3})?.*/"  "cont"
        Rule      "cont"         "/^(?!\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}([.,]\d{3})?).+/"  "cont"

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*fluent-bit*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On
        DB /var/log/flb_kube.db
        Refresh_Interval 5
        Rotate_Wait 30
        storage.type filesystem

  filters: |
    [FILTER]
        Name                  multiline
        Match                 kube.*
        Multiline.Key_Content log
        Multiline.Parser      spring_java_multiline

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Merge_Parser app_json
        Keep_Log On
        K8S-Logging.Parser Off
        K8S-Logging.Exclude Off

  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-cluster-es-http.eck-system.svc.cluster.local
        Port 9200
        HTTP_User ${ELASTIC_USERNAME}
        HTTP_Passwd ${ELASTIC_PASSWORD}
        Logstash_Format On
        Logstash_Prefix kubernetes
        Retry_Limit False
        TLS On
        TLS.Verify Off
        Suppress_Type_Name On
        Replace_Dots On
  # outputs: |
  #   [OUTPUT]
  #       Name stdout
  #       Match kube.*

env:
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: fluent-bit-secrets
        key: ELASTIC_USERNAME

  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fluent-bit-secrets
        key: ELASTIC_PASSWORD