apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-keycloak

resources:
  - configmap.yaml
  - sealed-secret.yaml
  - namespace.yaml

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 24.3.2
    releaseName: prod
    namespace: ecommerce-keycloak
    valuesFile: values.yaml
