---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-keycloak-secret
  namespace: ecommerce-keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgDo1ciVGOWOelzEnHcGXgFXhI2HVwp5bICR/pyErL4OSC6f2HhXCXPAA9bVTH5izagPv+rTfRMH7Vef40UV27YuzGqVAPVsFXsHWjsiez4O9+9kgyyNjQe9EpmoQMWE/+tyIoCJ4fcYwoi1o0OWRplrjIEnLhkiqUM6n/bMRSp+TmswUiC9ubXQcEdzmDaB/c2xgXRkjFOwu5ltvf8MGEswRi+sMtVpJEl0GDJAxtp4uvgQYNl7ITgSqadt08AHB8VPAaIxJMVuaemVKXnk+sVKRGG/LWqX7u4pCng/KRYXDtj6yd6wvwxB5KUvAGdoiuUckzNP5LVJSLMktTgjihdADXmS/LbNjSxVGdavqiKd6O/YY/DqQQQGg5F5O6qgv0gYXq4UE/JdyzsrQYqvS+NcO2wLAOM/yOuXek8111JTKwQuu81jTYYVsLpxZROYfhqS1S2xO9b8IqdZqQfkGgJCYGWRBwtdF/QGErRvgaLM2ZOZa5xs/75p6+Yp5UMmNQ8Km/pV9Hi7dBTI52Dn2t5k+asefEy2mJ2nhdEt7nEmkNTUhO5VvCWfH986P7yechrCFUegb5tmEzYuChE+zmHNsP2QV9Yn88rRgl0aIPKDdROzKeHSPSaTqcFdi1Wuq07UwRwNj7oYFCMdOWq0CpDmMpJiu+aubUP3uTHFoZ0V1lThSqpaPAswNl45NLKcv+eCVheiqBMLgiYXpa4=
    KEYCLOAK_DB_PASSWORD: AgDs2mA0YaW01kOrUKHxzoTcAVwQlPz6R5vgnv0X3KBDVpzMlaqYTt9/b6vM1Ea0LropCwxXK83Gy5JZhmMRHxPy/9v4W/USWgfr5b4LkTnTsoSZtnME0NjU/PrF0fnqMqs5zs/I/h/NRMyjCQ6B6thKvf3iQdjqcnkeUb96sOh89ZMLXpHzl4BJ9lftWbV5yThPjo/XOyr48BN8WnaaGQ5/702lDO1rdsLX27i+0tgeqSiB1VT0ERHmP8eRhbjkIhgeEKT+S4aa3oM1JqTpkWXLpEXJbNL0VsNjtIXUkJmBergPr5A3Pqb+AYiDmzdmS3+1TaaDILTer1YPQi3nGtFuXMgMy1PYXsAMkrqDZpbnQHWVCa5qw5lDM9m4JsTCpMr9xGItbVY+hoWZVBbGK1ci1TPsiyh2qUQgQR5xOkt5yo0WdF3hozkgrtKulswP7ErjGF65/N9roohT2tbBXu9ocLwbCRQPp5R/8pRtDDVu5zXiCIxnJNSejqFoGXDE/orsXpukGo6rFagccSyfT+JW2N7ox5Q7iBr274RWTttWoA4iD8aBY/OEbLlBnx8+RRQMHzfmchjn7sQRf0UdoCm9pTCSE4/89qvRnO50KVJEkrL50d+PLaivcx9Rd5QfXI1X60K+Q2I7vwcqSW8CzxS4CPACG+/69eR9T9UjB6FcDrX226NjK5iK93wGEoYvdrCAVFPf8EvXzcSGxMI=
  template:
    metadata:
      name: ecommerce-keycloak-secret
      namespace: ecommerce-keycloak
