---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-keycloak-secret
  namespace: ecommerce-keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgC8crdhfQhg7croqw02p8ZvRv14YkWwV8jEpAa0djxZuDSwtQkajoaimUQCWHShL7oeorYuI65bhyALcICqWO6wYHTwH+PJc3+7/H8HU+EXqIJwT8HNHZFBsFwQcVL3s/N6RU8BD3IXlDLcEfmCtNZXTzEST58O3wqbfDNjEz2ElexSzFsClpid3z1AQkhk/sy2x2qKkKa3DzipqdvRhfmloqWZln2izpQILYYL0YGjJKEJ8bYfnA508/8Yq62H/t1iQkWZptglgbBxQt/NUUO8/FdLg5QqudiNpe17Y+alHXbSLVaQ6ZyXMPxeB1B3KMfB+s3vOFX5CCJdJ7+rXgmo0uB9aLKGIcL+77CNUFMo/lHC2LtrIo/teoyNxCxv2FKhhOY6WviLA/a+vp4zj2KmNxe/jUE1ZmV/nWC/0G4q0m8y8wknk/ZKzexQgglQU5hLGv3WEIMUp1WnrlT2q6FN8rqmwcoZ//YSxeR/W3FgXMPY2/3izfCrtftu2/FggOcZV5haxPaZQG1B43mdryd6GgFjVh6+m+6LInnpsIxN1K4JnRix2H3duAqeMQX/KD862e0dDbNNdsClAxuSC9EodkCypFEnhYphDIlH8OKKTz1+oR6O7F8TZsVONKGKz8RUZNV5s1ooNbzQd2pqZQcqT+YqQNI7rCdaQ5giDaHCrBWINZR5yU9kqsndH7GDrQMTjW/ybsw5tlmgbJs=
    KEYCLOAK_DB_PASSWORD: AgCE1ss+oHKVFTtGsDGHd0GeqdpUsC4gSL5C6Glxu1GuW8XP+HsrytNxXSe/DLqudKbMPXu5iQwRM+hT4+UAuHA/sQaiSX1fpzETtQYgUf0JrwrsQB4uCScDFBW4rO1iz6QyYULvsyDVWh6ERhjras05+x6MGg3V8PXztuq1gBgqQYEls2cQFLeFwaEkxgtjsBbD+Xl699CtBggeJGv+ESdDss2/3Bd7EVZ0qU2aVp9Q4HbjBbQvhyAPymI8wJu/JiXrvN1Vbko31CoMt5QHJ0D+zBVipeJA/OutDim1+Fkxgg7Z57eQdHbHrS36BCFI3EiZ+ya6bTeDQsjjyCDBMWvLwUxBnSwRfMB53VFedMhb5VbJsmiUOaXMlYqbfTgv0hae2dxZl8IojRmwD+3ihzjLCnk6iRNiIsAxDg37Jxx6vFxzV5qrkdyZsI/Lai48W8H64eKiALg8HolCHSC9p91x2AgqtNcMfWo1q0bF5+1ayT6SI9tAb2ZBfKNMk7Sfa/WOy678VvNXVS1BlWoYOCUqyZDcNonIP5iQvZ4oqzd5ulBl7Z9QQjt992R8sNaXQubl+XuxHfaxo2UCufBTBBWvZX+oCjnzR/+jYYOzDSXGjn3BDl1bUu4FUmVzFs5HVFZgWHWmYdGV8Ea8la2x0KOW2HvzigekbLmlmHwkfocYKP7uzeQf2M6d5Ivzw4badSdwId9YE/LuljezcOA=
  template:
    metadata:
      name: ecommerce-keycloak-secret
      namespace: ecommerce-keycloak
