---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pp191225-redis-secret
  namespace: pp191225-redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgC/oFUypAJZJRQYFQR2wURtFGA5XNlBunBcm25qKIOwp+1xVSYGycf01yEMW1tficrb68KFjp0KbFGup2+WUZSh4a7kd2JRZVroIJxJMge7J8utTH+tZ/eRj8zKw6QYjoBHPrcOtADgXA3yQq5jFdVpy1a4umu/MOK0nucZHsKfsQA+bRC1uSUuW9DKiU/VAJU/3OD0QhNhGgQvp/zyns5Evv3/8YtTDfAvGBeqmPnxkv4d+mwrhKURM0SkLe+GPwK8gocQ6k0dURze3DGK89uKNQ6EX3ZjH7yS/uDUnpYfGnQqn7sxQEmRK9LTO6NOCkj0Odn/jK8Pg84vmkH72axpxdeQp8MYCfSZ7kagY/9jyyUFBJFYSICF45d/es5QL3RDbHvkujWDuNYr/3pA9EjA1kZHYk+BnSx+8qaDqapRc0LAghcyRArpgs97IaHSP0njayUOkLj54pMAwYdTqqGRLWjufwUoDWfasBtlwbHEvIjkP2XHlZiGMhIJxneH60Y8by3ZaddjEHp9T14+0u1p8sh2pls7YvuXj3Dls3NbWVk6fcJVBgt5vjqdPhOB5MRmiImY9QijUQcy1Wlw4fdADX00LMIRqvWPEaNqgNp5aT8NeCBHQxxTiBVYbVGGuQGJUhZyzfPE9a2DqKOyC3Ipwhm7YERSkZ6GnlV2wYgLgxkYc/vJF+cQcGExM4NJVndl4CcNd2e3JE83hA8=
  template:
    metadata:
      name: pp191225-redis-secret
      namespace: pp191225-redis
