---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pp191225-redis-secret
  namespace: pp191225-redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgCxJP8wBZHoAFSTydnbuL/WKNncuHHutLG+bQPdaTmq3YKigaP1U3WxgBSUwCebu0QkWrXq50MiesfQGfSfGyiMxH1Tzv+td+Pe3JgjXEsZLDde+XuXiQlm8QleFlIkLFlRyprra/5fjTIphFWDuediNgFmFzX8tt4fZaEgZ1FMvjmCUI3/D8/5z2+N/y1mBMM+J4tjQK+4fuDNs7VW07+blsuUlEcris0mqF3JLTK8SIJpIeJvmY9wXenuWr4EbPddqgm59213wad8UzCxJBK1jBfG6tk6BSlNrvOvL/AWqOzNwXvrttyMLLZ94qVgW3NQhf5PDUmvlIpFMelS/OwhW1YL6VUSaOxBpzFsXrNdTCUgTn5NayRamoiRoIPKFu0jtfBZWjatxwf0MFjMoHjNSXqO2kLQNOa1CUtOygP2FiKm3aV3eYNtu3SkYijBFC1zeBVqsX+ez2ATUdNxYkDchK7Wkrmyu2VJKKpaSmORy7En94J3mtl2FidCkzNuE+AkbXP5klcYmBxnS1Ymn1z7p+mpJYLIGMVD4GmA9eWazJhQfiaXntCTuCBU6OlHDTAoNEyTSnTzUPTzsGyYG942w4eBh9Ny/XUlBKdS1gayOxHyXYYoFnwTPSu2P9GxVY7COWP03J5WiuhMOPwAnUJMTNUY+Egt0yy5bHV6RfyUB3lrRyCnMHi8zh8PM8gj5ZZOKCArv8Sld5KJo1A=
  template:
    metadata:
      name: pp191225-redis-secret
      namespace: pp191225-redis
