---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pp191225-redis-secret
  namespace: pp191225-redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgBUxH9AJHHxzHK4B1So+AI9NhnpWveleeQp/Ue6ED6y2uZfjXb2uwauwBBfg+6dVSJwYPNilhp5JpPP9VioZ9nr1dqVSzeb9+NzA1CM89q2y3wNi0MPYb8HY2rvWuub9Su6JeNI+qeYtDXaukub7kZ2FK9q/PM/Gm7et+/ulT3ex1ElTyY8u9thBCpRwSvxpX5hKfI7OIEZkQQK1XwKEwqYwq3bGoyKxhEeHZT/Ku4rvOYH8MRw13b9YW9bMqqXVw9PKqV3kBTGPiR6tc9ArpVZHvyPCRoadUmFQLAJ+SS+urT3RmzIAUtWkMerPHs4aCYt31eZcNJlvmWnXtFwEqv1OcsLRNFuqIEuV17kPbAvbDiY/qQmTxwR+zQ6zNgx0u95JxSuz/RdCoqYWGkPR/bWkwRe2R0MUYYxlulym655/fdYQOQHbZnAHrvabmWakFC3yV1zLwBdu//bYddEAVx0Ijaw1kK86WjryTCM2tXUGVWpmOeqw58WNLEkvlwjg+eRd8k+H0qHJrYqf6Y6E96TU9PrfhVsjNkiXctA5iycyaJEXj/b+2W3T1YKcclzC9PGdB2lqDGr9vrSUvQbr7cxsQDpzfOPaPcJM5NvU60/23lqDQyBAEkyVWWWuZvhpREpbQ6HYapU/hSsUjJa/tiKgcV0sXEe/f3gJ/Ol+TcJz/25ths1+dLg3yqkdsgQwyfAmOSBaSRWh9+7gqo=
  template:
    metadata:
      name: pp191225-redis-secret
      namespace: pp191225-redis
