apiVersion: v1
data:
  minio.access-key: minioadmin
  minio.bucket-name: ecommerce-products
  minio.secret-key: minioadmin
  minio.url: http://localhost:9000
  server.port: "8082"
  spring.datasource.url: jdbc:postgresql://ep-fancy-butterfly-aohsjx0h-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
  spring.datasource.username: neondb_owner
  spring.elasticsearch.uris: http://localhost:9200
  spring.keycloak.credentials.secret: CHANGE_ME
  spring.keycloak.resource: ecommerce-backend
  spring.security.oauth2.resourceserver.jwt.issuer-uri: http://prod-ecommerce-keycloak.ecommerce-keycloak.svc.cluster.local/realms/ecommerce
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ecommerce-product-service-config
  namespace: ecommerce-product-service
