apiVersion: v1
data:
  CLOUDINARY_API_KEY: "954745818919594"
  CLOUDINARY_CLOUD_NAME: diqmhowij
  DB_URL: jdbc:postgresql://prod-ecommerce-db.ecommerce-db.svc.cluster.local:5432/ecommerce
  DB_USERNAME: thang2k6adu
  JWT_ISSUER_URI: https://keycloak.kruzetech.dev/realms/ecommerce
  JWT_JWK_SET_URI: https://keycloak.kruzetech.dev/realms/ecommerce/protocol/openid-connect/certs
  KEYCLOAK_CLIENT_ID: ecommerce-backend
  SERVER_PORT: "8089"
  SPRING_PROFILES_ACTIVE: ""
  STORAGE_LOCAL_ROOT: ./data/storage
  STORAGE_PROVIDER: cloudinary
  STORAGE_PUBLIC_BASE_URL: http://localhost:8087
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ecommerce-product-service-config
  namespace: ecommerce-product-service
