---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-product-service-secret
  namespace: ecommerce-product-service
spec:
  encryptedData:
    spring.datasource.password: AgANEELAQ2vLhEgM2hJg3ReforPO3oFNEdRSem6HafZ0+B4JlY/x3JIA4ZQY6AAYDWR3wzvry1oDHHnECX+YXX6CHVdZTUqzndp8PJd9Y5Z6g5tL/SegLwi7svQUQSLb3CqDRtsYdGB2Zh/Wqo73cOkrUlxr+YyGj9TLRl0q7ZC5y4dbV6la4beBJIF37HCQJ+TIktfWyIBVvPiUh0D4C406bNQ8JwxnV6+4RThjxGGjX8UIV0wVUbeh5PgpkSRAHaDxzfpjS4jCdGyMBOSSvEgGJ8ygTrqJlFl0HDxgOUIvWARy9wuCtTyx0jctr4GJceyLNTDLEcZG7v57x2OzSijklJHIN8jkP357HzV59S8QcxNikDlC0vPU05h3OXclyKg8C64IFwM+vuTgnQhHtH4J5jwShX0rNVWGINBc/FKHQw8pvkY9BmZuBien0SoRdXjrv2Q3jyMCtICoSlhseuwGsi6a+QEeaN7HDy+AyPGT2H2UoRaO+sECYz0yGWYs1MbefiXHDnIpsK1HxO1nm1eYA/Pi4MhoWnaTSVUl9mCdEsCmOG22KkOzyDuzNrGCosvlDihMhEiI6QuK9fzccJ6kvoF9LAI/pmMmG8AMRuivMd8xLvL8f3jWfhkUEjCCTRoLrrxUMqgPa+fzTIFzqDcgF01Xu27Tzbie/CnA/1SiMJAfji7uO3y9rH2ntjD08x2/6YjXmJBUBT3dxgKvp2CP
  template:
    metadata:
      name: ecommerce-product-service-secret
      namespace: ecommerce-product-service
