---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluent-bit-secrets
  namespace: logging
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgCI8KEk+b7edOUertK0xtfvYRMj4siM50NgQ1dM+e0jiRWxFoUBthQd5pf3KPIWXs+stHl+5y2rd05DAu9P+a3CqNU1IH88kOwaJbXq7QxuaV5G/pnSmL4+KZjbsRUICE/skAObxKzeRepeczs/mP/r/SHMrswGUBnjowWhwlMRYw9+chZgJtxqUfydXL6XszAkIvcL9yvpg2bJ8CV6/bhEPTmZRt3/B7UVH5CkkHpQX9IvjLhU0ivcIsYBcDw3xzDhjglIaiMvRzunVojoFgsoNP95np4wgT9ylrQ6ihLkyTwM7WisDBvAYi1wOgnscc9m7KfmdBfFc+dSadMw7XHwYtgQjPVgQd+WKuxRUv8H0uGOIS2+ckxd8EOyih08mkizK49gi4TCWtZ989ymYiAJPine9Ad8ZerMLJzIb9qIW+79vKWFNU8XjdY5SBQc/8pKFq7f1gsHBDWPYKCgGbpP5uN6JmX4Wie0pOfAgNVV1K1HaXY5L13+cNzhNVStRQlmCpsZ+VNO+S1i7c4suKnuuRnQwPMN2S8jDCK9Tuq/0dXhdIXTIpEl1PpdrtC0hjQKBpYHuxHTokG6Y9dOME0JX6QDxQFwfalaCxOloj7psqqo7Jz06wqHeE30Ul9WVXSWEd/G7ezNo+naRWurcO534IjUS4YUAXjaS5FnZEQlRAvJ5Xy657nxwJf/3dhufE0+EdJ/WPmZpbRg4pk=
    ELASTIC_USERNAME: AgCWVKIrVCiqIYWO6ZzAbQr4jJISbiJf0YakFUM+LmqBruDIMu25wMCeclsvCDP9nEncpfEnSPZanWDEsZb0jjKAp6HyjfFPxn1siwCqAy413CvC6tHaU53rDq0LdnrHX2x9n3z+4Q3LY4NXDLf/1b0Yr28fcUOG+CFUcUP7VKg+Ih+YLM+pHnKIMztyzyJ4apj0mrJk9YzAw87NZ7LLsG7yA93uFNub/3kz3ITK85RrOlIeyM3QpYH1ug+qnDcwE2vEXHymPMkjmwWApEZRyLF1TDUhrPaDj2yU5BrdKc0OvQCncOe6uTVYUfQ2w4mSlCB+01pDOalXEi1fXEXh0X+ZcVsfgXk2p7T4mGuoDcTZ+DUKgQkYLtzOJtagKkbLtRyEnJ5zAJheMReBMHCeXCpGhnLArXvOO3x3kw/l8zEZ5/eMI0mjPtVurOxxZiQK+0a8aNrb3luwfFN2K1sc1j9G0VeEuJWnENTIeaLqKoVoh9Ej1jED13N5sR4QPQyVJUF7vmj/lEkO5LD4QxJBpBZsPRvoyF92r9jAYROtIL4ykdJ/1SNNFCVQqCpdC4gi5NvJuxfrmKraPEtlilLWmoAn2XHdh+dC6/T0G9DzPAE1CPh5wlxHPfN6kmZCZdpaq0TZySegBq8Rn2KbYhXu2Mec9rMUvjyi1nuJ0c8iizVcQZucX1tTlMLMPoS8sqPgnVG1kwhTKmXz/Vk=
  template:
    metadata:
      name: fluent-bit-secrets
      namespace: logging
    type: Opaque
