---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-invoice
spec:
  encryptedData:
    .dockerconfigjson: AgCGWkDB/mxRv0Tz/dGD9EuoFffmfxrtq8hpqYnPkYIgqP/jpXpuElq7isPsmEkILojcaC7KQfSFYLeTtKchXUWk47txu/FiJ3noB//CQjsPPova8M2WNDlZ8I7tSKN8wnGzQnG1OMY0PARzIPZuJf6rUazAGRTLE3WjZDNlhU4fjBNiCU1ytQVdjdGS7+XcirkOXs/ZS1SLV2+noNinnS5fvJ4SbhRRO5r80bCdTf6FtHrIL2a/MaO30cJbTp0UFlhcPoNn05i2RxyN3q8I6ig9CXrIBpCJ68dH8r1ycLeNRrjkP8C2MKaBNkdtqGQ/xmlfJ/eqO+zJ/FvO7qUCxI53nXnbdq6nUkI0LPnfUbM3VqeHnH/GF/W9z4+su+Q9TV5AP9lZj8hQXtbWwKiGaRs/SQTAEen2L2cWogSPlXFnVha35O+p4sd4722PR+SvuvDcZ/mT9/h7KDNKcI6dYsHEW2el/YIHrKNTc+KvMGO5g5EQNTINMFz8OD20i/T7a/N12N87aC6BB6GPVFCzZi84uXESrdulEVutvAi97jxgpfklZ+SpJant952U8tG+SniFb7i/257W7d8uPBkWcYbiaej0IY9OWj2R96syfxl6HeLJbD5bJLhMclPRjZP0o/bSPfXijlkIQAP0jPrH8YiXuQZMeKqWpgyHfWDkoC5y5aN+ND5QUMRWp0T9lmv2isVyxfmRw704FrHYGhfBaecBCXr5wvEOfbss4XrNTcbZPEcSDgnGWEca92SOKelyO5w+VOJkJtsm2XZl0pUyWx2yxWgDROCvjF4Fd21oC3VY2v0dScjLUpKnK+IWMcCb+9yblHGB5dixSJXGywOb9BS0osN7pUsxYSKU2px+yZ1Tuas=
  template:
    metadata:
      name: katech-registry
      namespace: katech-invoice
    type: kubernetes.io/dockerconfigjson
