---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-auth-iam
spec:
  encryptedData:
    .dockerconfigjson: AgChhzta5AwozE+PMUzFllVYc1Op16Pp90OMep2+fvGoAKhvhLtbJ35v/NZp71ZrYtzjnpqSGt+w5Vb0dquJZG5EmQVv2BgMSU6aV608foV4FzPhh8bcbRPfkOZbJ5PVijQS68kAgAIfhJfp/NONNmlkHbRQXk8fq2VYjkkvAhWdnn4E58LS6oRCQoIJM64nhGJeybXQ13BeLlwQmttJ9qWsSb+JuhvVIoOpGn6mk+JA6B893sqqh+K8ZIj+PGe22Fg6ZXymF6t3YonUAQE+AqpyqxZZhkCd2cnsF3vOP2L/oIr12zCxKqZTDDqsIUt+hamJ7g8WfEpLai02CnB1jxofPfHk3+zFIbM6qRWqsd3hGdSOqJQdt/6CC7p8mhVhyVHe9BLJyFKs03D7tR4c369gAcJVxhODEcJQ1uu/Lv6eF7NFI5ue2x4s9aFqw61cv9NVTgjyAFLEdQR44q8+NSS9TJ+ojWGtOhOP+Q76KhAFTWw1pykQe6wMBN5cv140JREvhyIqsUrb/+wurjV9Z5RV7b+mj07dfKQn99fTngV17Td/vbyrizJ1fDqPy3Dl88JfF+cdf4bmgeQvRPcDZS9uoNIeZvhIRkSAg/PGYD0xJ2o+I+AwPhDZsCH/iqAxa7Gk2EtDLKP2OIEn8xKh0U3hnG6pwY65Vw1d27p5Y/LFuoBrqGU7XX22f20E2N0Zl3+VIZkN3sz9aCZUpUsHS85udbUfixOeAx2Ip759CPghOvpE82SJyBAbsPCUdt9kLETYDg98cRGSq0/bP5Gwj03EMaUZfpukBYxbtsf9bgu+y+cs64FvylAXsHEY9+wQ7mfLV9lB7edrGmqHveTAbvHWlp8reogqPy9L92qK8/2kIng=
  template:
    metadata:
      name: katech-registry
      namespace: katech-auth-iam
    type: kubernetes.io/dockerconfigjson
