---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-auth-sso
spec:
  encryptedData:
    .dockerconfigjson: AgBQCjG29l9UrWrXTPnrYQLmJKdwRHN/1FigKunPUfYudtHBkIbNfcDtYmjdr6y9j+H8WMi800dDOP1EDZrMRFuvpR3JQZWq8Dv16n4Ty32lNh3nWYAq+tzotLjkiH/8DA25J/C4QLJJ1LNljNIZipeL4l1wEM63yhWXaCxZDpBtBIy81KPm3jk2xSpyRKbmSAcCQQ0AhgADxPaMXiBQhuXcWSUnfHfcCvAOKvW/zj5Ypy4xChDEJkZZE74ukMAf1tiTtG6tx2EguoRX8wocvNYsdm6+ynTcbc0beBovdTu3rODKjv1tFXJH7lq6NSpg6ZMO8YgLr6ipyC6beQ69tWOBImowFnn9hbZWlyBjhNgUk9F5hWwfqhosj8rNW7UAgtyRA1asPhYYt3W5NnIAFrlu/JDrXFozxkVtgzcgb3+O96IB8C8l7E+irmihB9UZmRBUaB9x6KUwKKvEJuVBYnpMwbflEhoN1PHXgrbgN1oLmDIrp9a3z6vGCm1sC3ZshpZHE77/2GtB+vykz2UTlie0II6QQk91Fn5k70DlXLHo2RWFnDRpEqC0ViVdRT5xez8zcBrWkldrATFY5hWm0c65IvseMM1g5j4eSDo8bQbJeaOP90J7lb66M7eVzUDjX8861hDifSwqe7xESSTtotNRl/GZRy5yvd93QIyB/T+TGylyZes3OlWTt5M+nNBLYCmju4aYerpwiPYFrzRJUVTssBZq1XZ19z9a6rbrvgVeeuR3F3AkwjtNI4XFGOMyCruhYdnql2yDmITgDzRE3P5UdgCzvmz9A9+s1pfGJqnrARvZE5vWW3wBqKLnDQCU2nMfnwiSIrYFUzCvZoH/8ZSD7s1vC1d8qQDNrJGft4ioPak=
  template:
    metadata:
      name: katech-registry
      namespace: katech-auth-sso
    type: kubernetes.io/dockerconfigjson
