---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-subscriptions
spec:
  encryptedData:
    .dockerconfigjson: AgB2aRBLSYn3cdc8RVFBCsavheT07q7Cb9xMysExJYsSPwxT13SCN7JJhcp4G24INQ38K33M8Ycq8NE5sx5kFOOlU6pGko+9xQaxewP2NRoGyOTG0biH2VTOgF0WFln8uj5yrsNa/u4w5H4WV0jG+MgPMeyOxmGeIYka4xV5K+lq4xEFjHTQh7XR9v3oFOqTiIkX24+kREu6zOZnXURx+4Z2cc270iKdrTdZcNlRUnL4is+9AFRyzW5mKKq9qPoVKDi0b9aoEp5VznhGd6rZfg7oaZMmYf+TiCarC7DkZ8EMxALaqhLDX5ejioDbalzR32TIXgGGIctmljWe2LvM9nQ/iv6A0JAELxjW0vafFTBlP/VJ8eVqtnGLtdHCz+dJk0yODAkhq92hgnD69wMoumC/LK0jNR2YWZT1LTojuo6KaOxKte31YEr6jcv/HWZ9IysJGTJaVgtsj4vb0ETu4Ppcat3RcGbqahriwunEsvytL5aMFB8WEihQsq2Svpwi/j1qr8Tbo8VMu1MqKuBSA/DaYUoPVU4xdnaOGaQ4gAql2VyAn4ysiprRoCuPstW+uOf71oNw0r3MztvrXyiHhBbJHFqMnlWbn0gZJKr2FpOkJyIvGbEJtZcbujYv68Phvi7USo2Db1eQIzV9Fjb/SM9tiK8zLnfTJNClh2K/AAYlSnuDShk7tM/xkNbsjPQSk5Z7FFrerg4VqN19mcoO2fk2XVabb+L8b6/6fS7LqezH69Wf5jkWdNFXLiML5dSIRmXDHHrF0uRH1S50QU1ZGcOmw3OL26Ia1qCq+m+hHzTfcw8NRj7tu2ah2i1cF5yGYfGMxyRecP328HMVKDC1nw2tm4cBVd4WLsbfbghw1PdQAsU=
  template:
    metadata:
      name: katech-registry
      namespace: katech-subscriptions
    type: kubernetes.io/dockerconfigjson
