---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-shipping-service-secret
  namespace: ecommerce-shipping-service
spec:
  encryptedData:
    DB_PASSWORD: AgDGZNCcB7vOwGHoSjYybESh874klUhY/DDXCuy0SSXIUGrzsMcBOQzoBpcM9Pz70vi1KkQFhWi3SKe94x0FvT9unVmP0W3vMTKpxTpgFsIXMj88pHwVAwkVKL6Rr1rJG2ZmUDWAMz9EXF2fLkpezLFc9HM+115sj+nd8rq+CRRajR0hEGtkTJpt+5ixktcAbnqn5BNR+KJNM7plYL202dn6LaV4OLM35SABdkj4eozsLmJBhbc6gJ/bK8NY2EcxEy4dHDH748kEE50AD9gaDBUekIEIKA4GvK1+tYcbWkY5SSypMwMwKs5cI9q2I3JLOIsflu9VGlbA6eaJosogwgq0DsbcJRzj+JT2s748sdqmkyxzh6teV1NQNWZpkxZ1GIybb5Ww9sUxO8eEkgEo9q4TCho55AXOToh0gXrqSUrh+7DIz3yil9C0IHSC+hb/eqvvhPu+TEsstUkBEG5A5M8TWt2W3TfPTFgo3bK/mrpDF/TWQjGZkt7NHmDVr2760qjC76TPuEkwjlovJCHCEOVoni1hWSIF13EsYf8YbBM2OjwUHUhASLue5+GPQb0XYBHZtP3QWlY+ckLPcLNcV2Fcy5sWD1N7jxnycPvjAIiVkIBmTdSUeyZfxytS9M2CFt162OmOgkNNW9YQ3fCQwkMBjqfQ0Qey0I94c0RgsUZp11/2Jl5631K2n8i7deIUtvJA0k0mFyL9teVfcKs=
  template:
    metadata:
      name: ecommerce-shipping-service-secret
      namespace: ecommerce-shipping-service
