---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-payment-service-secret
  namespace: ecommerce-payment-service
spec:
  encryptedData:
    DB_PASSWORD: AgArSEQBjBlpIpWc3XWDWJLT5TeKTmznQykfDhk8XYdGHoconsBfffcA+5t9EOh+b1PsPKrzu9Q8gEgdRRIU6rRrW4Z0h1W45nbg8l44sz/MmwzHT0DWMtojPRQCfHVZTXb5TeIwg3PCw27Yq4y3/990HlK6y9TQm/5NNbFm9t7jIt5RnIEnsagS4liYr/ta2jw53vecHe9EqUEeUqNLjxtXZdLUMYNYgvI2FzghKwyan6wYy3YFG9Qe7uPuTrGxLCn0+DH00ClqIhUmbmt8b7OV8lgoz9h65v/3vu93NTGxoY0Gs4YFx6I4LMwtGnx6HtoeBRmYR2FfMNZf05zUQGPEYyr06wYvrlQx7u69czT1MQfmklG520sz929gqo7QmgVzeG09XK5JhMFEWoVoi7w+0oMqeC0xPOC/nwmEEhUFzroSe6FGMGWkpUl4Bu4KASZAyXl20ajTre3i4PKMUdU/aoT7WTY4MB++K4VVX1kb5vi8m84QzLylj81rjRRUCqOHEMSbEERk+cbwKHQYLk1SktkhDr5+KDKr8U8uoDHM8fgcuCjH9CPgv7MBLd/+XoQQF92qdy3MyGh8sLaGeYolbLfK3nygZl8tmE4FKfvVS2JjNgn7tnbEEMuknJfOTi0wI/0MoCatc1zxZAyXx/JnHpwa+wVPEkvxB7kyg696mtiEwwMZw8Lqr1c4r11VKny2zapnddgEogPRDQw=
    VNPAY_HASH_SECRET: AgDBGXyGxyLWuRO+8iknywhyLPVnxfSffE9CK37QZNfGnyMf//sDRlukKfauZDVqdZJo4DO0G+1PBUzpWMgHACh4uMW0IiiGgwnBKzJ7ExihKWkLVK0CBF3f/1m2u8u4pV1PAVJ9fwCffFsDGzpWeSHIEs3U/NAVXzQrCFM3ORZevWEfydgYqbOcxlQTb0P1CSlf9mMXFwMebTGLS5lrE3EV22bRgdTaQf0zWBWlNP/tCTGQ7WIxtb0ei3hbwpUFzHqgn4lm7yAo7WO3+ymy85bgu/3QtsSsAZcAdOiLEhFc22bO5hy4qP9ndoQRLez2AKJWsIHeyn+D1WkkNiV4ti3Y1YRwoObhnewU+LaJt9XvZg8IirGrU9KRxAeEGj1diJl2GkXEH96pIusLejSzNy0SkYdPEou0rfO2Sw9hhb/NAnzuHzY8Gr8mex0Oa+ki6GcodaMFi3Ar8ABhgZDXCYaob89LpfzG51s317aqNqWWPmoU2+zeNWz6Yrjm7nGpDnkpwe2plowm8QqYmGS3c2BBAbkxClvAARe0zLOgowqTmS/MbEaQE0WaspTe7sL6tNLbM4FhsUyh8xmpVeLwIQ/oVn0KnBjbaYJoyH2gW3ycDmxaojDLoCYSUT/pTHEE55tvx+Sa5bKq4FvpoR5NLbU9xICdFF6MQl+kgNs5ffnG3g3lphjmUc26jWFVYVRZ+gg+h9+gwryqt+e7QPrsDQ==
  template:
    metadata:
      name: ecommerce-payment-service-secret
      namespace: ecommerce-payment-service
