apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Kruzetech Nexus
      prefix: registry.kruzetech.dev
      api_url: https://registry.kruzetech.dev
      credentials: secret:argocd/katech-registry-creds#creds
      credsexpire: 10h
  git.user: "thang2k6adu"
  git.email: "thang2k6adu@gmail.com"
