---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-auth-gateway
spec:
  encryptedData:
    .dockerconfigjson: AgBageKWL9nWrvWwxYFeFJLNSYOgc9DRA+/os3frzzOo2OnT6/dfeBSWkyQiE77Ptx9qc35s7UUYtV7FR7aZIpgcW5O+yTKTN5OuqjOBB0JVDGaC7Rn8kkHZFOIUT5lRHFP8F5AJAZJyndtOWCedj3UVt8d6bp68IDMlis7pT/PPnaSvCUu+7QxsZ5ihjt5FndtilqOIuEQln7t4EjFuxUd8+Crh9CNULG+AyXZeDzFIke0WBGoIE7NsD+boCJLOUyQpgnWgcSMHWXISVEOZuCKTnVF+66tt1c4Ah6wTq5umQNCLTthur8Zwxnt5Q5jNza6goswvetjkjl6vsaMqHKAD8oJ9tR/RyjyYIBfuIcbZVksDmV1/WMC3jNLyy2E63/qXDAxcxMe81N/g9uC1foBgDNcekTjy5fuQGRNKOCjln/eVA43WVjkBZiwsr6icw/fMQbEfJvIB2pFs9pfuQdzViq6gccnVMvaRokxMKsJcEM4UwAgeczZ79wVmRddrvCRfDANm9zVzUPHC1Qzx1VqNnMEurb3sP6pNpX530sqxfaEUboTNKceUaEapPUyFHS11cum+m9SpkB8z+vLlkGi0s9CrgyUY9hBxvQtvPYUb5Qhrw6ChH7lfiUIL9oe3yD86YlM1BUpso5aegmfJq6coqurucMKbzlzZxNwFQC+LtbQZO96sPL++r9yGRe/hbSyEXAS4ILyYXl/8/eMHejfwvgcvN2I48+Q3QSG3ZZNJr2QjMM/wOAFOrYOtEW3RVYbDZIhH0ayusCNJJx0ppyzDscSQRKT20Asb1m6HKIZXvy8dUm/WQvS4EBdI/jEGkvPUXo0zsyUiI0kbFaQw9ZnGIqFH+126onfVxujPZUoevaU=
  template:
    metadata:
      name: katech-registry
      namespace: katech-auth-gateway
    type: kubernetes.io/dockerconfigjson
