apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-db

resources:
  - configmap.yaml
  - sealed-secret.yaml
  - namespace.yaml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18.5.18
    releaseName: prod
    namespace: ecommerce-db
    valuesFile: values.yaml
