apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{SERVICE_NAME}}

resources:
  - namespace.yaml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18.5.18
    releaseName: prod
    namespace: {{SERVICE_NAME}}
    valuesFile: values.yaml