---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-payment-service-secret
  namespace: ecommerce-payment-service
spec:
  encryptedData:
    DB_PASSWORD: AgArMIPTuNwhL1Y8h6DTY8SuksvH8FaDGQfFPAus6nZ9GsvjqgdlUKpJcZ2HJ7fcSUKoWZq72G+0d7mZRBMz4/Yyi9FA8iaZBVJjWilCe/5QxEB8QDvMFMo7ak6rLAonLG2vzUeKGwmccEMpqWkK80kIicitxGxDWeJCuqz2t5Y9Wa546iJfvppHHD+Yhdob3tVqssc/ToSYzDh7WX1e7B8t2mC6D2TypB0BpIjXqbWuhJr/fZAUtVVeQ1y9rihB1q0RkoR2Pi3U2awKFiK2hvUpzxsDUIqgkyjh4VgEryFv7Bp+Gkeg9GLUm03cyPt16iD8nM3cpF/esTRiDpECKv+OISeuE8NFSyE8j9RK7k5pQB9p1cop1Lre6Q+O33zplLxPTXLRBoQS4+gvla0Y7i7rAdmGgbtqpYiDqCFIjXDbyuQzs6n/nlTQ+N7gnVJj5cwg1nF43iprlKh6Mr3pYO8WvR2NYimtGyjTRHwALrs0PzAmvrEB/fdxt5JBh4IpxpgY2O/OqCPeRwnAw1rWCm8AMyyViD3tmLqR1RCWcgt5N8bIM44rkxMBo2fg9pFveTh8wZK2vUnMeUhjez2g8SQIcyaYBLdkGqpYP/fBuHMmcAbHmh1XB/AJmmL3cxLxc+D9f5OJZYonvj4UPK3jxWQAUOOy2vw+W16hqg9ee+voOmxf14J6O4KFiSW2WsXrHNvzc66eHbJg9XLjrvA=
    VNPAY_HASH_SECRET: AgA7qrRLQOkBJyQHwJFTcg9ooxgBpaBUAL5oxPzbTqJMBLm/PKOElwW9pYvCep1uC0n9uj6AzlKT/fs4FluTjdH5s6qC4mXdwM6vz8yGu5cQImVBt5ViKavbbma1aJ0MTDBYi2n7jHuhYMP9eCcVs0VR6Yzn8I0W27qo2CPbDvCjsURqe6qVdtle/n1fzBkIgujFU0C/gh3aF4Kr37CScgL1G6I2j+b2ZWbo4htVEeWtiPF2CmeEnyM/tFpckcKmqOKeOE8KEFtHqrJE0D2zMHYWYqpZDPE9n/yAStG4DXHVidnhQlTkLqA4kszqUPV4Rfb7c9NU0RbnqmAEO6kf3n3cBHzPX+UKWkZ2yXDCKhdLZjrQuRlfr0i05geVMFO1YRs2fiEZrzb33Op4bVL7eKpDP9M37xSrMB8OrvMz6Kx/u3DIs1MAi6KXMER0NcLyHyYuih45Gfgt29Rrc5wikJzZunjsGnbjc0i5yLFYPHNsFOVDu8D2+rgQ2eCYReVgaHcd0PvxHKFPxYU8eyOZGt9FjJB+nJxwyxOKNroJrN4Z2srE4Y8EamMjD88Y4vUM9xRpEx5Y3qWINn+oKE+oLlwio41uyYFxUqKzCg0dg+9PjXuJdSXj0kbwpMAw/fObpMWWpF5cpByfJeIITcMidoxmgvr3+QpK0QULI7DfbX34rWEI45YVXMBhYn5QcmxZDmWD1ibRY1sO+u78N8wScA==
  template:
    metadata:
      name: ecommerce-payment-service-secret
      namespace: ecommerce-payment-service
