apiVersion: v1
data:
  DB_URL: jdbc:postgresql://prod-ecommerce-db.ecommerce-db.svc.cluster.local:5432/ecommerce
  DB_USERNAME: thang2k6adu
  ELASTICSEARCH_URIS: http://localhost:9200
  JWT_ISSUER_URI: https://keycloak.kruzetech.dev/realms/ecommerce
  JWT_JWK_SET_URI: https://keycloak.kruzetech.dev/realms/ecommerce/protocol/openid-connect/certs
  KAFKA_BOOTSTRAP_SERVERS: kafka-3a12d0c9-thang2k6adu-d680.i.aivencloud.com:19381
  KAFKA_SASL_MECHANISM: SCRAM-SHA-512
  KAFKA_SASL_USERNAME: avnadmin
  KAFKA_SECURITY_PROTOCOL: SASL_SSL
  KAFKA_SSL_CA_CERT_PATH: ./ca.pem
  KEYCLOAK_RESOURCE: ecommerce-backend
  MINIO_ACCESS_KEY: minioadmin
  MINIO_BUCKET_NAME: ecommerce-products
  MINIO_SECRET_KEY: minioadmin
  MINIO_URL: http://localhost:9000
  PRODUCT_SERVICE_URL: http://prod-ecommerce-product-service.ecommerce-product-service.svc.cluster.local:8082
  SERVER_PORT: "8086"
  SPRING_PROFILES_ACTIVE: kafka-sasl
  USER_REGISTERED_TOPIC: user.registered
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ecommerce-notification-service-config
  namespace: ecommerce-notification-service
