---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgBqYQB0eSd8Yj/wqWt7P0e3Kuci9vO6NuQ6SXuJPDfCCi0Pa4galQn/6NxNA0cyAOArC8CH6gEG0q9Nk40xvdrI4n/1gDno1UDtu7K6qKFaCIXPyafESwDZAF7oTWqzeDL+mfj+VoeH8gcClmJLQ2SHh6hukIj6N3Ls5EmGJldJpM72xqG1VgvWQJIOFd3MPxwKrohmuOU4FFC0la6dFQya4+LTLf4FHTWhvz5ufQ+nhp4PdZrSTleraFsh0QUK3eJhnIUlVm9qdywHoPig/J1TkxYOnO4yeDDMJHBsSAo+fzqAZWeTUR7+iHAzRlFoZICUGMyWsRvuy4ktAlOU1PrJvke2/zcHyByYvZntMBXJGmh6rNZ95MI9oQhf5h73VHkxYGU7TMmKzVkKKJDW5qmURBVC0NniaIzyEScV1pPt4vLUnRyDUlK7GS5jNQOn3bw82W+rFkKy69+cBLNDIzWcXZ8VcBWE4sutc9YwWnINCs6i28M9paLv+5uk/OT7bxN+qze+vk2C3EW2FfvU+DGQIVo3heW0fBXAOU2OTmbrKEFyAiXZ/Y1faARilb/D7VrLUfDl6Feq9LjSXn5WxU1ygUsLMgzdOsjk1aWq1Hh/UoLNKkaBC/xhHShDHd22Bw4kHAzBYiaxxWM/qG1GhKI5+Yh/+M/iYkr3VXFvWHaj/7mwlUTgVvKuqJjm6d/cslwXdNKESNW7kHggm5Q=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
