---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-chat-service-secret
  namespace: ecommerce-chat-service
spec:
  encryptedData:
    DB_PASSWORD: AgDfcRBMXvRAUiL0P44Rqs8GSlJlV666bDJ7O5UJ6PiI5MaFVFM42y8OA797O/s4rKk4RtRyb6LNYuDV7Wq0Xtjh9EDAZhSCO0sEUm9vPoeYHBLsO/Yq3oc/dS805ozrISOqPTW7lzG/RhaB6oAYLmk5KXPbrJcAFmxUkJ2se+Xwj1mqF+XeeMncJ9JqtJw1v8c5/hracraQCcTgpq6HHj1HhHCRE5BXiaFVmHaskP4Jtw2I1sz5l15VTr0yebqymD0Bj3/yjthf/qrZT8NOiBIl58YhEhA9YAyp3YhiHMjkXYBPWwax/1Fn4AB9EDnYC72TUuZ5a+0ujDH0gzOkZKvRr+YJDn4uFI8KPB+SC2DkajqzbCvKEst7LhY4Na2LKtqa7lDHG+kU6vWOSOaiNGWsfG50ixPbi1EW0XuvjtsKBIEMgjr2XC8htnx+7tiqnc3FDsP9WyMZekJMMxCd0Xmnkpz/eJTzahlOdv3I7V4W2I9mkTC3e4swcS4hjptZJOXQTiYNP3j6JOe+AEVPWuKfphsiRI9/Ecsb/ILuTPDtlQe/UMSRpxQAMQ1vw8VSORD8oGaxRXKFRDptDWTCzCT50kPVfskSW4wEc8svIiFFflbElZ24hlkruhMt/8EoLAC8s2ZAafPMi4GDHBy49mCQWTAb+AQB3KQsl23hYG3RX1Ldp/6VWYOXSTNRAUvrcUoIXaM3g2mJIgIE/eU=
  template:
    metadata:
      name: ecommerce-chat-service-secret
      namespace: ecommerce-chat-service
