---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-chat-service-secret
  namespace: ecommerce-chat-service
spec:
  encryptedData:
    DB_PASSWORD: AgAcigJf+0xVJiCH5MGdiDzHxcmwdf0PEmd55oVK+S68t3hFj6zKe2uuEQKmBfkCVRud4Aa7BonRwV/yxmGFIO3FWzDIbplPp5vcs84KyyHC+jBfa3rfqR0z6uT9aNOCLl+1BajM6lzs+hZ9wtwJxFwItrpinf1FDXPwRVGPcqO2PXll11kGZNPVenW7SDtfLVEoleQo3p/ZV++CL2YzPGDLwTuAobLU1RC2WZcHCpPywcBEN1ydPgrjSfNfLEcACtaqDdkrh1fok4Y/BA9P0BSqOxdxzhJlglCfJvzeUYWoNTwGjpFilQTSteQBG7AIbMhAkV24HhkJfhfxzpMc08fvsdKTYbNROmeLS7OAHH9Q2OGcQ259nByojQipe6HoTtnw7xM03c2OwOR6W48sgdIJ/+Q0LytHDurv74xtuhkkwJU1oi8zvkun9bm/UtcMpxz2YiYuelNQ/9aV1rXyLqM4vu07wE2ZSfeUpOSIMSXb8yhjxSC1v6A13z0PLEvgNKczdYxFQbPJ2+Q2BEwKJXr+WXu3a8WAqzzz1sI+E4NK3/gQ2397RaUH8iwSx87dh850TXGEefATcOF3SEUyw56iqh5mMPII+Dfi0a3n6hs+2WaGIxEXDlr9U8gn0rQHmKa9lbu18cLPbxxAuJVIPG1Q2akFKQpFC44A0M8aqA6aMgAV8YJEMvChLjH64uCdzbDrmWNVPaGuqZFBCRk=
  template:
    metadata:
      name: ecommerce-chat-service-secret
      namespace: ecommerce-chat-service
