---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-redis-secret
  namespace: katech-redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgCKLuOCbcI6pzcrfbXPUalHeE+Rl3hvxoZgi8nViFIxFw+3vlZJ/TIGHErJdLHCfIJ2Hs+Twg1DaJD5RxKEUZS/Z1igVBxAwr7KtTq58bLKxzKT03kvnbjSb1Ll/AaSzx3qKEeljbGHZ8erzlokB2WrihObwF+lI+9tR6lnAM6jMQjnldyU2nE/bCAF+Imt0l0mYRtxzOMvsqiQEf0/HMc+05ZwwsjXLMSczt3AG4aXtGZfMyfJfFQkY7IWOyg//ILiQ55ka0iHcAYE4c7jVOLz7UUU7b1/qQO+mDpMWgD/nU4B4e+rhxYW4yzMH9h8byAn7OPgaGZ5tSjrrdt9J0VYf+aU5n72SP51b+RidGJ+cyO2AcSB7GXZOTxriJuzJt5JsHfi0xt5OLawKysrHwauxma1zz+QkTOp2hI16x1zmHT1SfdOMP5JiOd9pW+M64LBykdNL6/DPzs40VpNBDQINzMDIHkYca2Kl+lW6Yh3OSXo6b2LHU95K1JS/2HyI596g5+kT/19Xiu5jThDIq2LwwWuwnN5zOqLO3B3XDqDm4msAV0Gwb1hcyWcU0kIo1X6p8tnHD418AF9Ac9R4gHntQAkltSA+BA/9knBIEuZzP6DqDDqGdJ6r2TxqbFnBAMw8q7uUqgYJiAF8Wjt7fVNAfyYmCWc690N7xpbhOz1nTk/J5TPNu5AaPnXdxyai5+A5eQTj2x4PCImspmHlmO5F5CGXUksiQanSCh/+MPmAg==
  template:
    metadata:
      name: katech-redis-secret
      namespace: katech-redis
