---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-redis-secret
  namespace: katech-redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgA/MmYs2xQpVHAosLTmlH46yci9cr5qcYot3mB97NVAwpKcVuxC4h2irUzdJMzYGE72w/6BE/NP+cisoFN9DoMN5WjJFK5pqjEtG//LzgE3RCvP76USHNhnT+567B4RnwwkCUuqFx/C30CskzyNj1FoQDMikdF+EtFui8Q7RimHNrgpdfkDJZe417dAX4KcbJCiVA5xDWRZ5T4da8otgYxei2z9W9v2/oDB1GD4+V5f3To2s4ObDOeti9yBMRuiwMRAPWnunnSjHFp1eHdfsYh6xjSkuT8trToGR2au1tvd1BarTvSEDtLTU9s7lZmChQw8zSS6K/FeaWAH6O8b5HHM9cKpTN8FNyl+GkNiZCppDd2a7/Hc4YB02yVeQBgrJCZPd/moy2qwm62Y+GLfwZQ61wHnoeycXZ4rW7VfkfoMww6dmM2hTsfPCZqKTIhdeUoBplB0qCAOkxWF0e/8soHuWsOAiUJbDoFQRbtfcPYjk5lFjFfzDbGuyAfKwb4bhWiDwqtfTsyA/l9ZQCDdyKzj6FK+ia5IS0z6jwvfPP5BI5AosVyJDDfW0qkpJ3/XKstUmf9qjjA45DzLc3XDTsiZ7nhDq2/elhjHbhONT40Ru4QlhhL8tWVcVTeV1p4tKs86Ri/VGRAw1p8vteqo958u5vSJdXR2vKF6WrO+7oJvaO/wO76vjxjhoXbzLv4ViDCQ0EvTGLTzg3Zsp3LxFNJb8n5OhgOsd8bJyTtSsHQ/ow==
  template:
    metadata:
      name: katech-redis-secret
      namespace: katech-redis
