---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-cart-service-secret
  namespace: ecommerce-cart-service
spec:
  encryptedData:
    DB_PASSWORD: AgAWEwhEcFkwqVnJVHJxh4f2lBNRwwNUg+CblyyOw6y9bs6UbLVMJkrOuyEKLweAsBgu1JU2qnkaJo62V/opb4cONds2SQQg4tfKqMOh2RJs2+fN6Xptk6Fmm/OSpzK6b7Af5Wc1ntJujGAHtCN9zcmfFHdJsq52BgbAyyNmzjobSPEw0fDMw0pOGWAXoik/c1ekgLhXyE+X3zturJmnCvAFiPQw8H2RtJZ4j5BM14jCdqxNPVhdhib0a84CIhw1RizWiqTkyhXicW5uLVTO0VzwfszEBAnuhgFPF37aFIx9PRxWrpmdl8lyx/KNrz3h88AThDs3i1hH0Wb+Hb8kQ2ILg90MpzdoQl2Mj2qbELLwMvE6ZE3pfk4+rhfimgtlOtbLVlj4wyOwbHCy08KomkCqAhNefZ7LEKmcC3LHBWz5prAGXE+dgCRVTLh2KnG/k7ovDbX59RnQgY5DSAq6LBIIxY88Ahyd3UDGW0Ye4Z0wS+uSV8obp6VWpeZ37yYw0/WruW8x/Q50CpLLUt0CRAXoyX0e+O15hKlKZSch1eb0p0/LFSWJZeX1Jxa4Y0g04hLvcdHLz84KR5ci8ROMVmaG0r01brW5EwjISRvJWJ02h/DmdA7zidbn2TmzUy/U/7vJps3NHiWx/hh2tm+lY8tKELf5hun6m6bqEsI6gZtO3y/lGMoZ3Uh92TZT3pD0Xx5infTlbuzfH2CD4Uc=
    KAFKA_SASL_PASSWORD: AgAZrodYz5anmi3C0f103N2fF6pEepu5foARtc5YhxbzcwqhtPyuCHFdkPcyug0xI5g5WBImRnCXFS4jVEWWgezUonV4ExaPkNgHUqUoT2KeeOddmIgCSLBitXCwMMt+bribGDloiKYukpMpoGd8ZIeTPHmDu6axDramao3/wA53RRbLspA4SrRuQKLLIwQ39Pcn8PaqFlVSUnLnGI+NjCYsfV173Ym3DvoWSEo9tSoo90GWy5xI3EW/E2RuWNBjQe53ApAUjIYi+wukML/lCuqLyr5gpuWlw4FemYeB83Pewq2SWEj8B3BXVOLa2StaP7ocPaMCOipujY7TgeB1iRpjF0ROtRo9wsjIdbJ+VZ2pxu8F7UOxn7RrqABmLVFqt6i3czzD6QylHaJHj6KU0tRPRm5QZ3Vx1Pgif2i0C8nBDT4oqrb3iYD8rCXgpPW6Vhq7WAc1vLigxwJQq+U0+8W+O9DTR8TlGvmi36sHN6WEeN1cxTs5sV+FudbhKJhX2hmluKjUcDE74509kAfgVPSOd60XScYgRgamSqD5czMxaASQPgXINeBGzye1N7HGg9tUGNBYS8NXuO4Lxxa8bKg5S5rkLRvTIsBG+S7KzhdLLcDZKdYfta/eqtSzKbYmQGg8EJmZpfQLADGNZjqv8GrcAZp+ss1ax+xZLzxQU6hFKXgzrUcGBtQ8i0VjW4mvH6HJwKCLLnbbHlAozKcLOn2lgM971qHfqxI=
  template:
    metadata:
      name: ecommerce-cart-service-secret
      namespace: ecommerce-cart-service
