---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-cart-service-secret
  namespace: ecommerce-cart-service
spec:
  encryptedData:
    DB_PASSWORD: AgCGc79ZfGNA7LrzkOsAahamxpBMj++yFwo+MzNL6UbXbOr+nBVNpJDERO567rCdMi5lzplckHV+Pqll3pTSTnKZb7C+Vx+6VoALBwD83JIzFTqzrUuiIwm52aIXztCFBZm6hIVrrZYShuIxXPsE2XXdXynHZ/biw25uN5R8V24r+YtFlt3TnHtKsJl4TerNsm0wsspCBWVqHNXl0va64H/OSSgnZxMxHjx7DfnngKhYspiZAEPx7blEPoHXA2NXax2oTEa3IF1fIG2NManCX18LNhStweYh3JbvDYpj+UlpfIH+a9rx+jadC0J/UQG9QYQ0y9vyPaM8DEAB27pEiHgETDhdj9SLmmqUaNiYE8ah/NK0o7LXGt/llXVmCJHerHpftVeCWYQY/mvCkrvQjs1G4qcl2YP0J9XXAm7cGneE0L2talTJLCxg8YB4SQFdW2mHXIa1p8JNtvmRJAMYJ7YTK4yq9VLeh13iqpLgD2ZOrxvhAOs0wKNEPQXxOS1fDq9CBrwKaMnChYBMG2JmF9WENQ02HDmBuMPDzn+zCgV4c4JbSjElklLOCeeYccOm0EeWusg32517Q97ioAkZdJTiZ+ZIUaMGJbB6agJOAaNPCHSrP132Es1u5j/Q+xpUTFMLVwGY89RdJoP0zvAfbg4qnvXoM4Vf5oeoqh4ou4Wxf16+EV56mlnk/zQZvEqLdJDydzMsoP3hAykdoZUqBWl5
    KAFKA_SASL_PASSWORD: AgDGmdZxtD9tM1VFsx0Y4CWcJWVWstSu7cDasij6/uEiWN22DaVnYAeDaJwL+0soW2hfbLQRbdDwetlZ3sKBflc8K+3uRT7J/rj+84GbAr76Nma4i/czQKST5Y2LftQfvs0AusWmr385g7oiLSjr90CUyvzhardWiVtzvWJlaiB36LsQ6RhjJDuIZBMRWjN7tK8b1oqJ+FP/jd9P/72KFyPjuyQlQp9glKtu3x7P8ddyc8JqcGstJIMWNEVAFq+nwnahyEkm3IGlTvJ7ktivXPmcZgN1B7C/VFzda3Yo0ekD1rKaNCYk3r5pCldNRXw/qQNTTqLn+5vF28OimOnk/p/ctKVk6Beh3ucWQJageJbFCKh8ruGmAFT/X0qs3S5sB+mgQBQdxqiscy7zWs/3scHYGpn6VjHcePbdEdNp6Q8d0zSsaXZL4qd3vYlf35pchgrRqqijO8/haQ6RRDr/Aj0zC1o5yKOlB5nKwdK+pWkEKdEYtScseRv4nhJZ3uZbD+bx7WdUrzsyP+3xTT5yWUKAQ7GVnFDH9UQeEGdzrPHH+W/cPn5a5Kqg1tct5mCFtL1RV+/aUxQokxu6pMYE7127Wc8QgLAg+humotR1hdwQjTHYn0c2TDOM75JWAEtz6Y6TaGORuVcPZ6Hf9awrAX7oipt/fG1gQY72ljfOH8GPZNbfPiRMEyO4Ins2cnd9Fm43oIkBwFNd0AmlEy2qIkCQOmr/wpdJYVU=
  template:
    metadata:
      name: ecommerce-cart-service-secret
      namespace: ecommerce-cart-service
