apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - matrix:
            generators:
              - git:
                  repoURL: https://github.com/thang2k6adu/kubernetes-infra.git
                  revision: main
                  directories:
                    - path: cluster-dev/tenants/*
              - git:
                  repoURL: https://github.com/thang2k6adu/kubernetes-infra.git
                  revision: main
                  files:
                    - path: "{{path}}/values.yaml"
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: backend={{ image.repository }}:{{ image.tag }}
        # argocd-image-updater.argoproj.io/backend.force-update: "true"
        argocd-image-updater.argoproj.io/backend.image-spec: {{ image.repository }}
        argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9a-f]{40}$
        argocd-image-updater.argoproj.io/backend.update-strategy: latest
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-repo-creds
    spec:
      project: tenant
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/thang2k6adu/kubernetes-infra.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
