apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: katech-nexus

resources:
  - configmap.yaml
  - namespace.yaml

helmCharts:
  - name: nexus3
    repo: https://stevehipwell.github.io/helm-charts
    version: 5.24.1
    releaseName: prod
    namespace: katech-nexus
    valuesFile: values.yaml
