---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-shipping-service-secret
  namespace: ecommerce-shipping-service
spec:
  encryptedData:
    DB_PASSWORD: AgAqcHnxsYls5NAB6t5dms0kUflRWqAieI7no5i2M14Ru8DOSclDotwrCZM2ZlVe0gxFY+vmFXINKaepeP6fpDKn7SmHHb6A6OVkWT788aDRfXliZzBeq/g1j6ldkL7dq2glt52WB83wJaqBqZNN1ihW8cs5IuQY7hRSmGo7IK+APpoatMXaZKCj/4HRBO9pCLm4sirGG9jIx1MobY9xvPNajiFCpE0rzN28MAGYkFAXZmfgKwg15Afha8GmZ+H88GIwLygXlGKW53HpvBdDZ3mQ9jc531l53VnACedy60G3riCpcg5nMkVYmwkJXvjXjCNG/fJL1dsOa35cQiqLomNj9ypyOsfW27y+IOzVoNeAVy6oBAOEwbG6gr+KEBPiVA517Eo4HOcXKW9AHjMN0UO1fB96jkw1R1UkkezaCGm+Mk9/xtEW8suaUl2lEukJ/maIg8KbkrHNpevKRs4wvMhR8G16J12S+89hbZE6WN1ZH17pMc8ccSsqtQlaf4HnpEk05QIQC7ORgt4a98Dtgj87e2FpBqHe4B0wrdRg6A3d4HQOePPdB5vtokgKYnUiWE5gq91NbN5YQl7GVikmLKu0+d/I1aFaBrRuUEFnhxCKJfbsdIkqV0c2+cfRva4b2A71n7yTdG9BsmT5i5oiHSljDX4ELP6d3JQsIjBrM65fJEe3/KuRsb9FByPu7XUcDqIi5oWOaukvz3BWOVA=
  template:
    metadata:
      name: ecommerce-shipping-service-secret
      namespace: ecommerce-shipping-service
