---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-payment
spec:
  encryptedData:
    .dockerconfigjson: AgBvj7RV/73UXpK4TEG8RVw3HWCbTzVinI1kMnh8xUZXqTkSsQu7g5EVuGXsTYSvwqifbDt3Pkhu5GIIj3OP3R1DKm7doelJOY3bT7GFFpax534lIQpH3HQTpTjE7yJeb2D0GA1mRrfq0ZVsiFkV8CN44gi0fDD3/nWOSi5Az/YWVyu85ALec/8vjgBrWUjcfbAiOiQD53JlnFKX9uURvx/XamqtIoxhsT67OMmq+woAP8+E8fYKkfbBWbCSSNd3OgSUrdnkiH3SlkEmigQCYcJkCFLQDNtBxUZR8l+oH6uEsRLAIfhPCRVYAd3otigoL3o5yPKFDWuWMTEeH36D70MrV5Y7ZN2zas9Bjz35mJnVxy+AChvr2eC0/UxQ0T3j7Z5uHluujW/YrMn7TMVUs9y0Vj67/50VE5gl8bHCZ4H5XELLdjGoOC0GD6GAnKEsKCtrDoA4Z+TSC6e0Vrj1s9XJAuvrZvqClpll3iJkoIAR0rqqOA/hgLJ7myypld8aPIV3yF8tBbn2sFvp8HFEy+u7+LrKUSaXfLjzaKxV01NsLKdSHOAueGOjhThVF9lr/q5rcDwY5FYwulAr5jKR5VsMjEYXQWvJl7gzMC4+XqukDfIWRFURYS9P9/Cavu0Cx+UoYhCZEQ41Q81xj8I7TCDMQpYyPwSF2tcWvnG3TnFyc7s+nwcBBRRVGRNVlpA81ztemsFX3EUZUro3/R3XrEOA72G1ZEWw+MV9ok/8Ct7W6pRK2RNaGTt2qprywfigjI9UsLbJBF/QIeUDCgJShHhC9RSElWmvbVkahQZRMyIxzE/stJ29kptJgq66CdGPIzdlXdc/opbZpIsKQ6O/MdMqZIaWbu4YzzwGypJtzBVSIDY=
  template:
    metadata:
      name: katech-registry
      namespace: katech-payment
    type: kubernetes.io/dockerconfigjson
