apiVersion: v1
data:
  CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost:8080,https://react-fashion-gilt.vercel.app/
  DB_URL: jdbc:postgresql://prod-ecommerce-db.ecommerce-db.svc.cluster.local:5432/ecommerce
  DB_USERNAME: thang2k6adu
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "true"
  JWT_ISSUER_URI: https://keycloak.kruzetech.dev/realms/ecommerce
  JWT_JWK_SET_URI: https://keycloak.kruzetech.dev/realms/ecommerce/protocol/openid-connect/certs
  KAFKA_BOOTSTRAP_SERVERS: kafka-3a12d0c9-thang2k6adu-d680.i.aivencloud.com:19381
  KAFKA_SASL_MECHANISM: SCRAM-SHA-512
  KAFKA_SASL_USERNAME: avnadmin
  KAFKA_SECURITY_PROTOCOL: SASL_SSL
  KAFKA_SSL_CA_CERT_PATH: ./ca.pem
  KEYCLOAK_ADMIN_USERNAME: thang2k6adu@gmail.com
  KEYCLOAK_CLIENT_ID: ecommerce-backend
  KEYCLOAK_DB_NAME: bitnami_keycloak
  KEYCLOAK_DB_PORT: "5432"
  KEYCLOAK_DB_USERNAME: bn_keycloak
  KEYCLOAK_FORGOT_PASSWORD_REDIRECT_URI: https://react-fashion-gilt.vercel.app
  KEYCLOAK_HOSTNAME: prod-ecommerce-keycloak.ecommerce-keycloak.svc.cluster.local
  KEYCLOAK_HTTP_PORT: "8080"
  KEYCLOAK_REALM: ecommerce
  KEYCLOAK_SERVER_URL: http://prod-ecommerce-keycloak.ecommerce-keycloak.svc.cluster.local
  SECURITY_KEYCLOAK_CLIENT_ID: ecommerce-backend
  SERVER_CONTEXT_PATH: /
  SERVER_PORT: "8081"
  SPRING_PROFILES_ACTIVE: kafka-sasl
  USER_REGISTERED_TOPIC: user.registered
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ecommerce-user-service-config
  namespace: ecommerce-user-service
