---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgCCaoDTXX9ZC+te2Rmvh7uyG1TO5lV3tOa1gZTKk2XpmRcsEJzbEv6VfapOcMc52HKhL+fNlJSmED5BA0jCY9/IxmVqA5fjIrQWuxXcA0BjvHndhL+wWgQ5bKW079r8ncBrsuKAfTY0xuIZ6w+IgwAmQ8MsvjPwSfYU5y4jFDIFyyhndiXMT8FO/Lgv3q0FwE5zMoP+r9YRomoNHpMj1JwJ0K2EJbBPJQndubAu0u8R1cb3D60Y+mnLKWewZjfu6lA9MoRdhNzCvnCxBcudokRRHEsUbQuxZwgNxbddF/G3lGZoLm0zRGK+Zst4yIkzXKldNtxVfHgLNeaE09J9bRjJ2faUP+VAOKWhmOIXihIPISuB/Ntv1Un+Z+j3qVGkirhQLssozuI2mWGAOkozZP3jSmZGkg6XLvV2H5dssLJhoDdYTprMeN3M9nuMwMgLuJE1lKQ+8AArY/KRZ5p2QT6LohXgbTi9AA/EPzWzzYOGsBEM1G8N4F5t9sOGQgLs216sZhE9SrgbHs9iKNwmDqpThJw5qvkNpduIjD89m11lD//9UJaKPign4RqrTFi7dlogGHpxTIYgx5Xk9mLMxVEsuVPZO4L4R7Y/LdFk4vFRGAVSe69DboBZ/44kZL36quC+HLjGhfrGgBiHW6Zx/8Pt+3T6BMctYO0sbQVF504iom+kYUwOW1WBPbIOYOfkqmQyUVs1hQ4YJBeOJOQ097i0Tcyu
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
