---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgAl1k/Pr8N8EZqw6J6lpW0ZGEbrfrwhtHLyXHlDnIgPmMaqsAy2EwRp8ucE18rw90hrx2dQnpUtg5VxinYM52threE5fE5n7cm9lzkbYlTqyNEUJt3Nsy2JqgZ7jMam6m2HNhOFuNT0eE0ERuMntrte82j4kELf9L9eemKOAf6uWGm/5pv72QB7ONQytHUDNQfxSzcKpL05Rrxb3PjY3yzW9SEDsngzqEVim9OGqA4X88kgcgVVl+8mCmIWVBH0z2l7doGywKW0noiAagLCzq6ADIqEIdhTq/TJfTR6NR/9gc8uA2S1w57fAZ0jhJjQIM5zsxDI1JA2g33n3eIPMQ/0gOXupIIIN59+IeW3uMovOZpeOTZXfBQmfUBUtdcVrzF6dKN+oWVY13t9Lfl1NeT0Ur/DRCGjzlp2wRxnAM0BvrxhCpwLQovRvbFiBxBY6Al6JRPywjRPn1hULlKesOHBDFg5sxkFx+ye32Epub3mQqpffcxQFELoZIDebo1p9UQr6MAg9/9tnyDWCcVi4BGmjV3z1OVPAhjc6a9/w0VJvUvHY6ksVc++roOYNcdyuwQPuwJc7/I+TUSxABx6mAF56zCj78WhfH0zBargEby67eveTfo4lSfICc2nmYE3+UdYIoSLFVAVap+tGTZNoQRH+UWuhgQXmGmAB5fckkVZEEaviIm61+6AVOIVs5aDauUO+aDMPbxVblDthhbXVYibMF3p
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
