---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgB5FRlQc4uUCIW/qQRUk6n7ce9ncdFlMgFBg1AX+n4APgFVa5H+JJICc1saR7AAqvekqufI2sTvVEIkUAIK6+n+XM+6+JQG84Ch9IR70nXfuyY5ucN6BKTuXsRN8XiZSV+RufHZRN5JYfQa3YaRJWP1VMd3pmJx6JObleUGmz7tM2L/S3C3T7Mjui4vTl3cr4oZ8IaruKIG2TasHv+YFY8XO0mokIDH+L1Do4FrABWotYOBoYoD2d4CG/6BtRlO1xR4Ps3GhbgXp+finnw8GQ5bjQDcu2Y3VwkGGmba6bcIwTK+KBOZwRufQ0t7YfEmCfqB/srkBtSHT64G89R6Jp1dt2yU04+DfFLjQYYNjnt6FjGztv3o/3KbjLw5/mmXcJ05YiHStlmHM2Oy0KOFkEMpWSafHUpO8N7k5NKy5yqgYkEIXBe5XR9iElUKmjh0wKVIgC5U8MBlTKrFUxqcmYFb8FVpAr0PIK75a3ygTLx9TgarEKS9njbqHr5/qZWcpHXU+qHkSMbSsjLQw1YRO8Jguf1maPVMmR1JKhlmiPX8A1Ow5aqq6FluKslwRu0VA6e++yNvX2vfVg5xfNStFCzQrJgvHS7AHiQDus5wkIvRyq+YziSQy8iWom8NrUOFNZI1yI5T1iWEnLvigtoZtYazEpDAan1Vz6jrMJgQNPEYkFlc9WJ0AN0IfCGSgIPDWeeetUbn6h85yJQH14Pn+h94NqCW
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
