---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-socket-gateway-secret
  namespace: ecommerce-socket-gateway
spec:
  encryptedData:
    DB_PASSWORD: AgAY7fe5NH28DUfMfVKEIyzLjnBr1ZiWw5keObm123jv4Ohen896CMNQR5tXMpdLcqNcLnCFqkOH5v5yAnIiW5e2jsJdWgiZHJfRvvTiNlRbRpnTLpNtxpw0tH8DqfsEmnr6GepQucv05QClFfcIAd8hMUMkPY/pQArnqJMygp/+I8Kb1Sc8KFcYyIb3fjKKMp1F1elLoCA1pewmk94/EDQQtt1S+jDgt4J2DQygt5rUQ/qBhDKRaARdwQV48ohf0a7webwCnye2o/kXk2R6tnTyi0jfpfZ2JhdwTmAflu+wTop6PpccYA6cTPf9iilZH0OaQlIP3uuRJjwaHY8hft/EN+K68YQ7NjRMW4ndTys3avy79fc76r4L1kMLLgYydGKRJb+58diylH+mIS93yzpajeNKYltK7YlrtLebC4usN1aiJo2PgN01gczdSavHgoiIMa9OXjn8zevLXXxZD6FqhTOMMn6nC1V2FUUJcn5D8GOBjC13Pnt0pD74xYFdSGTRqCET+EtqCWcM+V9i98JdFLRDUsur6B0jPZri65wD8CpJeEjBPucNX5yhwFzw+/zU49UOF13dyL/0Jh/9hoiOZh8TFijR1n3S46FlahVBWqUpia8OnBt8sbd26ls24jcQdBZq9LrfHoPCaoa+GDvy7GlIF6+/RGBiqFByBQveZb3TkQspUH1fQXzviH1G7ABrBTEEWgGqZNi7rWY=
  template:
    metadata:
      name: ecommerce-socket-gateway-secret
      namespace: ecommerce-socket-gateway
