---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-socket-gateway-secret
  namespace: ecommerce-socket-gateway
spec:
  encryptedData:
    DB_PASSWORD: AgB+qwBTqb6q8kV4khgEc5IKy1ygUUUjJjv4muvSzDWnBMF7pwt1GK7kzsoor6o4v6l7CkCi2pqZHBqx83gjEWky2VocQMlzoBHXwKRt81sJN0JfsR4LxkdtUda6SSGu+VeiXRjiSqkTgys6UE3ngF92DP3b7PjJ3pWVPZUCQ+TsOTL3dWFlPE9Apd4bgdDB1ixSnhARMHqgDF4hJoO0eLDrRz+ep+xOMykq1YmD/uffGZb5zabf9+5WNOHCR6w3Rblu+EGbZeA280zPlUIbz1Zvc59iwDEIHOuXMRdk6DX3tROkdZoPEUZvhP3ib+h+YJhUzwRF/ryYRTaKQNWlZr82rulAM2ShN7vN/H0PQOqwIvjb0JNpFCQA78lCseebRflcaOZVVpS8yaRhJZTbbYVcBeqYejvILUY2xyfWite2I7Mj8hnTJMpnFBhbyua+9C1a/MlxBCVzFf6MMpzLf0DSeGupQCiLyBADrG3XnoGIbLCSSeYH4nBidgu0a8UsKrgYHspKddo/twd8krZiVHqpECOrTV8fG89mj1lUHy/OAM8hdvhJ+fPGzlZWDyooH63lX/DCi5s4/lzHEsBA2vERMk4DzHrSe7gbevZenc/APqCLxUZFGi8brfq+izvANOAQxPnfwxd6zCWkZ7TsMqCm7Bw7T25PDTeDAfpb3gv/ruxo3ccXfskuAIAJIO+KdJuDil3nINhLzRrdoYE=
  template:
    metadata:
      name: ecommerce-socket-gateway-secret
      namespace: ecommerce-socket-gateway
