---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-socket-gateway-secret
  namespace: ecommerce-socket-gateway
spec:
  encryptedData:
    DB_PASSWORD: AgC82oYgC4tVV1J9voJnMuBG9G2KbVqJuwQJlcI6UNcesxRoRrcHupFsF2rfZMTXpffv0xzi5vcX+fQCein3v6kIXIsc2M8UTl3axBydX0y2MaPUNx1vB0MjP8v2pmhSC6uiEC62rlgijOMo1qJTIFqrz7DqQVMm7gm5+NL7ovIjyFsgr+CzrNcXAD6VoWuawdhJBHM4w6Ynz1aFckmI/uTt3Ej3io1E9eukjzRGxMoqMTiSuvQHq/DNM6GHK249PUmrvaDw5Ecvr04fPnr47LbbaJmK2nQYL3XCxxFFMMVjaq1eEPtcNJltaQsfHWfjZgQWxVyrNSznWbgJAIAN0ecizaOHbn4NroXEW9naGgxLgP+OUIX1BLDZnDGGMT9McGRsNE2T/lDwjDI75Smtp55Tsk//4FqzP2ActCej6J3IJ11uv8ycgoYOXuCqulnBt+YkZFsj/0y4/aFINoBIxSxbUiw+4QxO5EfEkCtb4A94hp2H6PAK7XAij+uoIXTGITtLz5zMKpHGRzCF2qEqIoGMc8Sr13WrQEDZ7ObCMaLr7d/BtCquSIglQvMEW2hwwpyXbWPY6yggYCr6BF1G3Q0cZETnKFpmxq2qOiuT8JmB8MsVJOVePYOUpB6H5nnN1skfzD2KUa4eJz3unWy9cVb/ZZ4NqIbcV7HzdDzkQ4Az7dZeBULPb69acIdPzDwe3u6rTJXmIzP3D0DYpK0=
  template:
    metadata:
      name: ecommerce-socket-gateway-secret
      namespace: ecommerce-socket-gateway
