apiVersion: v1
data:
  VITE_AUTH_CLIENT_ID: admin-ui
  VITE_AUTH_POST_LOGOUT_URI: https://katech-admin-ui.kruzetech.dev/logged-out
  VITE_AUTH_REDIRECT_URI: https://katech-admin-ui.kruzetech.dev/auth/callback
  VITE_AUTH_SERVER_URL: https://katech-gateway.kruzetech.dev/sso
  VITE_GATEWAY_URL: https://katech-gateway.kruzetech.dev
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: katech-auth-admin-ui-config
  namespace: katech-auth-admin-ui
