---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-auth-admin-ui
spec:
  encryptedData:
    .dockerconfigjson: AgBz2wBeTiMfaIo5xtvm0s/kJKHiQ+Sl7xDqy6K8B1+/b2QuWhjWhPiK1dX8MnpRC9rdYFtzY53yn6cyYv6UvjhBKg/DQZx9FqiSmbQqPfYvE0mXSnnzkmXgM3C/T/qBV/SXYffn6m0ovZZlz8VRnAZo4NLhxRNSRk5VolVNUQA19s3pHvEoqqyI7VpNdO1Sfln75B6AZBfL87zg5Q87DTrCBDcHT7Hs2GOOa6EqIaRC9efEsVaVjVkSmvfto9S8WlLeX2CRvAmgI14zBgJ+NoHwNrhamiLI6npA+rDEXoJs6Br9wzLo8jNfMy5sEBbGXOUKQFSM+o0m7MxyfmB1t51SncqpjSIAt9kEa5HoBUTRLGLYUYpgHfM37kuNy8bl5Dw3CtNEQ6Nk0XaGb7aIz5Yte4zz27bsRmHpipXUXZ0HuLTu/IThkTi7hAfRpqJF42b+dP08CKggpdXBto2TB/JA2O9/ounQJ2+eGN9N53LYFxe2ge6Md04ATexccsZbufHuQLSAjCbK5DHUwZGV/Z4MHTMSn/22sqJKMNMb9M3qJWjK9RfDZDyTd9dKADLwvA3d3RSFK4oC28kwcZVZq9sc/8tTnYwaTI6/VozuKnsrvIFu4SAZJ3sUam1unR95JnqUH5zbvEW10w8Yf9TE0Zpry/xCFzr3RQ6huS2QtZq5dK/FvvmD+zqmSFlfVnx442QitFh6P/ybdfLlttPcuuic8GIVo7KWjhcHzrYJo8GcTnKw3mi2JNtXZq361u8QRqNgkf+ScNlr0KGDhsqtevK5GZD7kuwOniepRRvVeWIXdSB6XIVJWqq3HcTkz4fMbWwS+uIPZda1nzopRSIf8pSiq+3/k17tUGYUQZFJ7h4AVyU=
  template:
    metadata:
      name: katech-registry
      namespace: katech-auth-admin-ui
    type: kubernetes.io/dockerconfigjson
