apiVersion: v1
data:
  AUTH_CLIENT_ID: entitlement-m2m
  AUTH_PRODUCT_ID: entitlement
  AUTH_SERVER_URL: http://prod-katech-auth-sso.katech-auth-sso.svc.cluster.local:8080
  DB_HOST: prod-katech-db.katech-db.svc.cluster.local
  DB_NAME: katech_entitlement
  DB_PORT: "5432"
  DB_USERNAME: katech_entitlement
  IAM_BASE_URL: http://prod-katech-auth-iam.katech-auth-iam.svc.cluster.local:8080
  KATECH_AUTH_JWT_ISSUER: https://katech-gateway.kruzetech.dev/sso
  RABBITMQ_HOST: 103.172.237.33
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: invoices
  REDIS_HOST: prod-katech-redis-master.katech-redis.svc.cluster.local
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: prod
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: katech-entitlement-config
  namespace: katech-entitlement
