---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-entitlement
spec:
  encryptedData:
    .dockerconfigjson: AgA0G4gH/w/iGofVlXXPri0rJORTHvTY6tMAfX7h+9QZVrXQB3+uYRKOWQDw+DFU9sjP5B0njpBzFgPLjNrPZPeLAfXx8ZKSS1ylYrkV8heOPzDj8LPAk6vPzPEqnQ1B/970+uyPr3B5zlEtpCFcUYwWpQYBXqIgdPkm5T67uHw6XjjslrcroxVM2x/+CcX98bJdMRPkTDxaMgtaNufI7++S4hcbGVv2nphRCB1w0x8/RwmNIMK5Q6QDkYjcuO+BXz4VO+23TARksPj+H0i5JmougwkRDtb/bJreimisljYwooYDOzsJLp9UxYMoXkmHxhIfNnjiLEiJ2vO+I2MJTNIuZiuGY6n9d4ZMmr+I6FojJPatcrsdT8N47CouXQiwTwnI6LjBvCr5ighMIiAJp6aAN764xHzgnh57Gf/OfRhYUOrOv9e8IKBp4c7pEaTXaN8iZ/uSM+HPUThE97a7aj3MiYahgUmSiWqxALvPKZTMZY81uf6dRWmySm36zWP2ZyLSNmb7wEkdZSt4tYx/5YaC9MBH3ABYidmhUm3fYPL//dXH97M3nypb+vTbzd3ziHwIJQeqxQ7OB0wpv4+zL43/TKFWIA86cvtDJaFDmvDQRktRn8YQBbtQfXVkfevP6OXOxbpJwrjycVZYjFlFlD2cRZegAtWaFuCd+BOEqylwxRiwvrWa/jynx74f8oSJjUoDY1lrN2hyi9sr4s9ProLcGmdbRFPVWyzUXs34WF6oSMKUyD251Vrg+KOC18AWcD6s33pI9VQ/eP7kelhsiBJkJFS03vmS4iKc2/JPYi4uhY58DWFBC41YVEp0htrMvBExbZJ2zXcFpJFOxSoMrA+bmmXJ30+CyGSQ5AH7XhYVnl8=
  template:
    metadata:
      name: katech-registry
      namespace: katech-entitlement
    type: kubernetes.io/dockerconfigjson
