apiVersion: v1
data:
  AUTH_CLIENT_ID: notification-m2m
  AUTH_PRODUCT_ID: notification
  AUTH_SERVER_URL: http://prod-katech-auth-sso.katech-auth-sso.svc.cluster.local:8080
  DB_HOST: prod-katech-db.katech-db.svc.cluster.local
  DB_NAME: katech_notification
  DB_PORT: "5432"
  DB_USERNAME: katech_notification
  EMAIL_SENDER: no-reply@katech.vn
  IAM_BASE_URL: http://prod-katech-auth-iam.katech-auth-iam.svc.cluster.local:8080
  INVITE_ACCEPT_URL: https://katech-admin-ui.kruzetech.dev/invite/accept
  INVITE_WORKSPACE_URL: https://katech-admin-ui.kruzetech.dev
  KATECH_AUTH_JWT_ISSUER: https://katech-gateway.kruzetech.dev/sso
  MAIL_PROVIDER: smtp
  MAIL_SMTP_HOST: prod-katech-mailhog.katech-mailhog.svc.cluster.local
  MAIL_SMTP_PASSWORD: ""
  MAIL_SMTP_PORT: "1025"
  MAIL_SMTP_STARTTLS: "false"
  MAIL_SMTP_USERNAME: ""
  RABBITMQ_HOST: 103.172.237.33
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: invoices
  REDIS_HOST: prod-katech-redis-master.katech-redis.svc.cluster.local
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: prod
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: katech-notification-config
  namespace: katech-notification
