---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-notification
spec:
  encryptedData:
    .dockerconfigjson: AgAcut5yH3V+q0TfPyrQ01C4E3Cpe8pRQilOZ0Z9RwPQf/tkxTpdh3ENEEQXZ7LfDrtibSINxEGh1rXml8C4mlRDmzw3akReHHeVRU97Mp90ZLy/Vpuu+/V3xcYJVi365BWasDC6ARvvBF+CSD8rLZYQpLnG++QTjqkn3f29A881V5ezdvP+9NVhhmmm5TrbcotAdrx7gJ/q39AKUaGCpVjHUy23iuFdX9fTAMktKmrmv3sgQ2EInPgkENhKg3cFsfnsU+bMVFtZKy2Z2N5PjZqd0QqB9TF+pffgJYl0KxUT3o7tPgn044BeQMBMJ+dpJAifXABdE/afpLXXg7KkUOWcyyku59haM02uJA+Fx3pFApdf+ZQIDCbNuGpDOcFKc9+pBm1N+J1YTUWUSmmnXUF+ciBAd8hYedmc97k1i0jFGPZ+3BEt4wVBWrQ2WkQ9Am/ir76u2gc60BTejsMMCOmLeQh64Em6OCGbh9nimwX4RI6tYmTEPQ2kOzs7va+1xAPOx7p5DWh4RBV4nNX2Z2vSN6urhnFyOy5RJ3T2WpnfBZKXGQTC2pLdpLD2oNq3LIwG1eYjQGEYha5DUbqROzet9xXpOqxEjgVHxQ+q21b2qPAvOkH6e1WW7laTJ8lQIjiw252U82qE9t0h/h2NNmfo3PyVfmV1przN8Wie18sGivEZrEsOGv6id+iRtdDHM4lPYKBTZIrXDjgLZFeFztmA85Ak5cXlfpAjT4QS4sONOEeNjCYI+9zfgVrR4Xcj4ZKeQVvxSvsYGGoa8CrPmzxC1DM3PSM6EWBz2ogsWvsT7hAOaNJiS+CEn1LQX0D6xaw4hqY2ueow05BPRtOOvIY/lEjp15RIIuKYM+jjLaMfptQ=
  template:
    metadata:
      name: katech-registry
      namespace: katech-notification
    type: kubernetes.io/dockerconfigjson
