---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: katech-registry
  namespace: katech-notification
spec:
  encryptedData:
    .dockerconfigjson: AgANjgsPAtQyHZE7BLQyVNAYWO5G6TXXWMiuoNk/Roy+xdBPtMamUEBjQWbeubAgEOfQLCzamyDDLxczZGcMo1j2GkbT3Q9cdvaKk+5TEMUvXsaIFQX5e4Em1OAmiAj1aa3KDxik1ZuDc4am2UGv8KnetBcRCxwbT/TqxkERJ2xDy71TfSV0hYs2EyuteRHW50DqmRcHZcmOH8Z4NcxBzRFCTOMcsV9wHjcCuQ/jRVF8xA3kgszv/XN0ZAuezDNeq3HxbhRUofJZs8bnePevd/9aFFLBqO7i3RZRlDE5BmPbOJjTHSRjZcG4YxfqAPtNzFqn0syk4GFkp3F28sskMIOWyU+9tVcac1OoZqtMM17hMKARzXAgKxFpYJZGRBnjEdAeDW5Ir6Fd5pKRnKEJFwmqqdbge3X3ZAgVlFlRlJGEia7quCZWCq2tWMUSFEcIZfmd/32diyl0KaEjy7604V3BpouANSKxbwd1t2BOowmVx8aD35i4IPlW/uxxQd2poWzpSxFnWKbErF3gDI4c4H6W9xVswvq1Y5t76a+7djgtDE1kE3VOpvsD6isDDdTSM9zY62AGDcEVDYXDACd5uMvg/643Cw0dLt8/o9khIqzYYvsl9ki0WjfoKPW0kZoGD0axavYLxXugSnqp8QY7AEgQtW5jZgyXZHf9DHULhuKne9OPmN9Lw0tJp5E6QbBD/R5q2cahbf5bOHMqQLtb9W3swHNWd0Okn1hkqd+iglmnP2cclHRss5y8bURTk2/YYhY66VNTV6gn4JkJXTFqPCPAa5MOIQSLebyQtiTu3rR2AS8Z7Of/4kWRwwztpXlZE6qyS95Sm4qdYKKx/eyFz3AZplfSg473/9URnQ6+LVAiEFU=
  template:
    metadata:
      name: katech-registry
      namespace: katech-notification
    type: kubernetes.io/dockerconfigjson
