---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgCpKvbkIo5aQgPOwMQt8BV9SJ42HX6T4Zx94uwPZy3eS+jWRihk+hU/4phajVQo4jRRwUYF8aMwGfxvzVFv+VlZD7g2lZzVft76TiZ59KBRMZXl0584x/4fzSyNJy77dkhYcUf/Xsx5kxDijyBFXmUQ2/L189lCnHRxwr57PTKrtEpJzkHjuJLFfQSfJRSoV/5FSSaH1m6piEiv3CXOgwP/WiC7FUYIjaeranc0mj5gJ2T3RCAe0TzVKqkSvfbTZoR8mq3qLgq5fT/LkWkvg2lEk0QF4guGpECd3TqZnjj+YVjo1admdVx81ZuEjFr5f1Ps9NvYgWyeVgO4JcczEmuOfg79iwv1SUEw73R/MmrNyN4/zD8JPBSvN+8Yfynopur6yeOWlwkkGnWKx2CkQ71ADBV5EbBMuxE3452zV2ql2k0ahsd/lDl1AAIDlIWe0K+opy22wn2oyuTyBzo3YplXLTU43unR6bC/QImyU0bzR+TkksINGOC5f0R2V3cKB7lWpvralcjJxjybKps/p/4mUPkybYKptKWKSNOlpb1Bx8V+wcdhd1/dOMbJfDvG/U2dJtKcc8ubSawQU+RJUyuPUvSO2sVWhVENLKSlB6rSIRR9eDspS/Y/4QU8NpxSrdUGjBFN4NEVvyXYhDjmfdk8pgOEq0j+a1nTfokcdDVkn7x7OcvpWCqYGSsy1CtsIZfLSlkdPWxnSao83GbHoD6G
    KAFKA_SASL_PASSWORD: AgAunw34kSRNiQUJYr4XK7QHnz7aOD9BSH/zlSs9vUNZtrMk+yD+NtoAk71+Xg3ZiJ+aL0+lXcomPrBYgxwWlGYYgUFlm5Rz4eRvkxa7tn8IH8VZcG8EU8TS5gyatgpLuYghdy4f0Fz/IwvU3BPum/kKPTOTCvw0OFxEGSktLCFChAHZBmdT9n+lpM5zlJdpLjEKIZps2HKknr4a+MQX44QfNsRvsvrGM/JYq6N4VPm/03Q5gfhltSnT1+mkWTxaeiBNocULee6NwK5733gAZLAZDiGsRyVDBtaUthDAV15ZYp/IaCAlaC4kT8NxncXKBzNLkQZubsCcVmZPFn4iAd99YUgnouzM4tzpVCVpUiEARWv3BGgqhCpg1nSJqiWAH2GfQBWQvXVysYhAz2ZBHOxNjC3ff8HPF/4JrjNhRTH0VOMtSwSAmINn9dQ0iSfNwqQCmuKFxUlVuWOKv/cSmMSrmSBAjeewQq9GLx/vy9dFQeFgiA/LJbwqwp7tMF/wF8a+NaIvulatTnNuUHQbAUIod+KVl3hql76e+ZM7o5PoZkG28JxROsnlaQdl1bjGCcOP65WBsTmK1vPFj3dVUgo02+zUHNODHSQsHuWd6mSVGQgSm+IfoKflm1QL4o8PHIrrjLMS1Qj9RnHFNOJlY0DZviGFbUGxA46B//bw6reQM/UVHNgXNfPwniOYaGYnDgAQbx/aoj//wcMoRxUq47cKDFIgqoMuuyE=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
