---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgBmQU69soath+vyPE79RmLcOigBNoNP5sdl5A7JJpXNerUOPLQbImghc5O6rqBCN0fzruAKbSigJvtolFrnf6HMJlS26g8NsOYhsny/opZQvbrChabRN/+8rvSvYRmVFuP34fOu8ySn4NXqew+Fp68eyV+G2adRClZUDWZSJ+PdoD45Akbj+iVSIju/iVpYA4BRh+1QaTBv0KJldHFD40FacLHtfVs5I8tpV8BtNx+W0imLvUmFEncjYN9okmVHJrRpfJPztH+x3HIZk50tLXsNK3X61In+0Nx0Zum1+6jbk6gkz4PqQpOD6WG8bJczTm1uQvcof1TYz80+G9GzSSDpWE1eszbPK9/9Fbm+HFke1xTZOL+AwbRpAVb1ZQzG2uwBfMSpNmxdF4je6KrgYDMSKWKW/x3Mf2d1lV9NfwpaqWbDyxphzfAhYj9l24nXBkHUeCT1+uDcZfr1pzZk+qu9c5el6c/q9chGKnvsiNgsqk8ZVPcJyzgJaeKppD2P0mK3Osc64wlEHdpMUEY/aXohyas/CSPqM3DQUhYZKS0/gbMTy6IG4qR/47N/S3LiHBNWa1Qglig49wAQDEB8Uv2pw40QXl5y6TMhSquGoMkODXWgJ0wHmHLRWNPz4U7JL9IJQOtlQ5lvZxbx8Ve6zMsXO2S8aRa6twAEs1AESZIphZ1mXl6HmZ9eMGPxK3ZP6thM4Usy9+q40luzgxs=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
