---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgCEqOtLUoX5QPBM/Dh2Kz0eN4eH9Rd4U2iBD+YdN2eNWnE+h9mGx4EN/ZJC0QmgArMpI5UH5bucuTZXtVpqnIMIjKHkZ0u9AYnmKlwwe3zmVYnIqaOjHrR1TOeEMOuEiC6/JZtWTQsY0YuRAbgbbm2B23WxE6NS8/1j/UfvzfQdTYck3ttgJMW8f6hCFrUrb7T4/DuZXhZUUJwhjljGuTWbJpPmNgpZI3J1AAI3hjiNOzpfS7f6jodIFTE/Ou7W8oe0h7PK7XztYNnZ8UkAtD/1vIX/3tX3QQPNQGkoKSzkfN+X4f1FRDW5cnW4Gpr9jlvcvwiGGymHPrLLIRGHhU7o9Me158LBDqcmDCp6M/104jAURl0c3Z+LRME8HFzwQniA6P9bGjMc6oP1F1pIzoWJCrxdKFYo3r83XjFzezN9mtlXYAYysuhYlAsyWLCeWNQ7V1CtVvFf0bTqEhWqqT657ZeXad3n5839A3hkWhnhAVnYevavX2mV85naEWD76qV4e9F8309YqsprvQszpyKjbFLaaNjPZKgbdWibRUgi4koG37uMGakDYrXoPhuQ6YY8xUUaFw2/pOB3pfed0EIwkIcMVT/UQA2D1ojUe9dqIMNromUtcOnv5oFth6ia75i+Rjxxoq4hduEgsGKshMXyp/a24d0tP+kHuU8yb8D+nlDpnoxsGYBH0OFgNdjskl3ZMmf1JgtDFJhn5LQ=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
