apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://github.com/thang2k6adu
  username: thang2k6adu
  password: ghp_xxxxxxxxxxxxxxxxxxxxx   # đây là PAT
