apiVersion: v1
data:
  LIVEKIT_KEYS: prod_key_v1:ZviWnN4VkiWfJDj/xsHGd1gtqRCeyPvpXugXvLW4WrI=
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: livekit-server-config
  namespace: livekit-server
