apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-livekit-server
spec:
  template:
    spec:
      containers:
        - name: livekit-server
          env:
            - name: LIVEKIT_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: livekit-server-secret
                  key: REDIS_PASSWORD