---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livekit-server-secret
  namespace: livekit-server
spec:
  encryptedData:
    REDIS_PASSWORD: AgCbAgqmnSkt191EkNIvdqRzOq0skWRSftMauAStyc7ayPFJusDSXnsIm0cM8LgtjhAJq7CpVc9WJJw1YWGP50jG5SGFhWRh/vrxBRe9hGSZfUycu5CIt1Gk5HR2TkMSne29howCFMf2CiKZYJSnhZGILK6wdhi/23t+6XGfmFsmsuGSxg2G/e7ofr9CyLS05pCZNVqa9R3ZU9XzDnkIJBYuIeLc8EmDthbsAXspKpHRyGqptNFojrgwYWv0btv+1AKQp3fyTCkian+p8FrTXc6A7wjXepCJrjTrHUk9Jk4uXURAuFNpUlM8MyERz3vT4RoNTRI1ehnIzb5r0ycRknyRhWgBOjNlLhr776F4GsPujt9DkyYTXArmBo4chP4TKEjgRTxHtzBrQNMVa8SBVNldQ8TQJXibbt2Tr3nTPgTKiY0FyL/77+u2z+Rs/rIk5r4w5tiHTC6YOlw+9QNGqwWSCQirzEOsem0aftg1hd11Xa+rNhCqil2v/YSh31ltT/2xnnbdEYfG14LnYKns3ISC6KbPGuLBjfUYMccuoScS5xn3gTs6vGqLtdsofnaBGf9pXgjrsqydTbSGr9fpf9KtYSLFKpdoq17DFAsPlBZ/7KlpBxUzETSdBzBzuCmhcOtH9DwFLxadGdIcKV9W4z4ri7hxklA1oHH3H56VAaV3XxCWT4znVzoNbFrp5Y/qwFRXTLhTG96Tnk6FigeBxKmb7AMy
  template:
    metadata:
      name: livekit-server-secret
      namespace: livekit-server
