---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livekit-server-secret
  namespace: livekit-server
spec:
  encryptedData:
    REDIS_PASSWORD: AgBI181wP6K9tmFNl83lRnbEn+eghvHYd3pS4e/P04vgJUwahjg6nEydDvkS0hl5+8HzG2cqvci1rxLqiXGu6ByLmis8iSK876U1b0ocICg6FyUXzjz4A2P9F4si5flSfbgsVK/3wRA7RF1S0l9YImm8tjd/vrWyW/iRAB44MjKJbLNw3Q5TJVU69sIEFC9GY1xjPYauawqoygAC9KnUM3L8aCzRUBhFmdAxynTjT6yUzMwY+YYIPE2nY2s8jXrx4BxGMrXZ8h2kat2P6V4pyI6pCmSlBvv4kcciD7+mTh/+ujBU4VdIA1U5u2zbqQ35WKSvr03o/SCGAAXxBOnj21SfhfbxrSyKW1aSLeLuacvmjnlOb/zRXi3dxQ8PW85OABh1hw7BT0ArhYN43vIjGVzddL9Ka3weJVhYO1cmmmglUEGuy97m5hWBqahe1LX3e7zCx20cKumT3BNU68+40/EWaA5H+qByeIotrMAMf+4I+nb4knRcZnO02VzyC36zVIfyXLASQRYGoM2b/mi4EijUUyHjjOQdPiwiCHx2NoQ7l/qIsWisD2b+lC3NCnRorm6J1fEOia5vEwCai+4Ln6V4hR7ur8v8VO2IzL9MckVFOyEalSeeYOX2TEfEmRzdtIG6KZvi6iMeIl80xe03m7W+WO9LIPtm9SMPpiL9KBQRw76Xc225BW+H5aR8W8oc2nGY35rhfdlcFEpAGRPSNaTvrMJ9
    keys.yaml: AgA2ypzF8Sth5tnqzodqEsYGIgT99uElxelHVT1Q3Fy41pAZYEpNr5+2YMRjWWgaK/OhRpqMy3dk+RMAIuNRxJjkRVSPb3BxFt1y0A6wuXadtysd5TkY41fs2APVjMExilcySkosUdfOidTxWLI+sME86p8fjILGg5WLhxd+LzJsbmnZPLWk9sL5F5dxFHcVPer3AuyKjW9GK2yGfWo66suP0ShdrGHDiEc5/RmSRvs+aX9YehHgCR0eK5ta0AXHnxHyeBX+OCCEzmqCo1vKCDP/pvjufKPSVJDccymDick0og+X0a9XlJPeL7+9+z6jJikDJzFGIeP6iR7vC+Lahxkkfptf0YcDtyRuLXguOdghUHM1dfDmCMCao9G0qPr0qBoJBFgZyd4QU4/whJcoS8MIrIEqDK5UsQbwyBL4zQyACoEihOEHN6pTC8GPs1r8z1In7ZAJr+blg4qum9yV2JZFJpf+pMLDFvQBOiqo7rDMTqeAYSgn+xxtz516SEwwDzFaB12sW5yL5cFdk6eA35eSTfgpC4tBWYv3MnyJsRHNdHhVjeuJA1HF8+l/DEgR4Q9256r4aRJms1p7a/ToOggtrRcbxD43U6jHwgtAfc67iPpjN0IZVxcJONaA0er8KnWUV3S7K4KfiGuo+2D7Nlm0LCuMxBez5yEmGeb8GTHrBWEvpCbXmkfZ+IAwLL8azCM0Dn+IC6ithIOvtAeKlu5k9rY8NKxKmxvWSRazUyz0A2zhlt56B278fj6qmbiBaFAs/BQeSQ==
  template:
    metadata:
      name: livekit-server-secret
      namespace: livekit-server
