---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-socket-gateway-secret
  namespace: ecommerce-socket-gateway
spec:
  encryptedData:
    DB_PASSWORD: AgBiqwENWQttz7HoqhtU7+67kCboD9oZI4WRuKDjOh/Q97wvdbwJVyHD0m1cG1FDhFR3SHUUS40HNPgEKFGyG+5f77ELWMLIAfskHLJy5AD7HqIUsLtv6+5csRXiAlZjGnr6BxbFkpM0PyrLIQPKETCp5z7vrkm4iUITwo+FO53z6U99yVghEh2Bxvfc0z2SPNsJFOEYofZpkww8Zb/qqGCLeK4Qb634erm9oRVJshiFgRPFv8JUIZRU/tOrNz0lW2wx2H0lThKQ0LmjQqmJ0Re763zeskXSGAuzT6/NxBG8Ib4ikuE83rmWvNvPeGUj1oM8Ewk8uYDTxNNOF0wdOYO+l6QxjoTkIwmSm9VSRSYD0mAb7agiO9NBqRVCQQ4ID6/apOayPqRvrdMwSoV0YxtYRqSgiafpdmrHhbKmy/T21Z4+EeEniManPIJ+DCIyiTH/8pKpjj41mfRLVbk8UsN0F2A303acy9+pLZB2g+PYAl/zRP6cUjXpRRYgHAIvR5HX5L9vTFHVQFgVuTdhX10i0PRVcVXtryFCqiPutK2JpIwqNM6XDzvrgJOFP12DiNbmkC+K8RA2n71NfvCpamF3853nCwRpFPNygNijVPWB17dSPKSML3ib190lEU87HcRWUsyPTadToPEnNcYmGpXvNOBTw5WbrvI2z83hphIw+AMfsWRh7f8z3X9HBsZfFCn5f82JdT+tcOqyV6U=
  template:
    metadata:
      name: ecommerce-socket-gateway-secret
      namespace: ecommerce-socket-gateway
